"""
Color palettes for product photography prompt generation.

Organized by category: mood, industry, season, time_of_day.
Each palette includes hex colors, prompt keywords for Gemini/SDXL,
industry/use recommendations, and a human-readable name.

Usage:
    from knowledge.prompt_templates.color_palettes import COLOR_PALETTES, PALETTE_BY_KEY

    palette = PALETTE_BY_KEY["warm_intimate"]
    hex_colors = palette["hex_colors"]
    keywords = palette["prompt_keywords"]
"""

COLOR_PALETTES = [
    # =========================================================================
    # MOOD PALETTES (25)
    # =========================================================================

    {
        "key": "warm_intimate",
        "name": "Warm Intimate",
        "hex_colors": ["#C8956C", "#E8C4A0", "#F5E6D3", "#8B5E3C", "#D4A574"],
        "prompt_keywords": [
            "warm amber candlelight tones",
            "soft golden intimate glow",
            "honey caramel warmth",
            "cozy burnished amber palette",
        ],
        "best_for": ["fragrance", "candles", "home decor", "wine", "chocolate"],
        "category": "mood",
    },
    {
        "key": "cold_clinical",
        "name": "Cold Clinical",
        "hex_colors": ["#E8EDF2", "#C5D0DB", "#8FA4B8", "#4A6B8A", "#FFFFFF"],
        "prompt_keywords": [
            "sterile cool blue-white lighting",
            "clinical bright clean tones",
            "cold precise laboratory palette",
            "crisp icy neutral atmosphere",
        ],
        "best_for": ["medical devices", "pharmaceuticals", "tech hardware", "dental"],
        "category": "mood",
    },
    {
        "key": "dramatic_contrast",
        "name": "Dramatic Contrast",
        "hex_colors": ["#0D0D0D", "#FFFFFF", "#C8102E", "#1A1A1A", "#E5E5E5"],
        "prompt_keywords": [
            "high contrast black and white with red accent",
            "dramatic chiaroscuro lighting",
            "bold stark contrast palette",
            "intense shadow and highlight",
        ],
        "best_for": ["luxury watches", "automotive", "fashion editorial", "spirits"],
        "category": "mood",
    },
    {
        "key": "soft_ethereal",
        "name": "Soft Ethereal",
        "hex_colors": ["#F0E6F6", "#E6F0FA", "#FFF5F5", "#F5F0FF", "#FAFAFA", "#E8E0F0"],
        "prompt_keywords": [
            "dreamy soft ethereal pastel haze",
            "delicate translucent luminous tones",
            "airy gossamer light palette",
            "gentle heavenly glow atmosphere",
        ],
        "best_for": ["bridal", "skincare", "baby products", "lingerie", "fine art"],
        "category": "mood",
    },
    {
        "key": "vibrant_electric",
        "name": "Vibrant Electric",
        "hex_colors": ["#FF006E", "#00F5D4", "#FFBE0B", "#3A86FF", "#8338EC"],
        "prompt_keywords": [
            "vivid electric neon saturated colors",
            "bold punchy high-energy palette",
            "vibrant intense color-blocked tones",
            "bright dynamic pop-art colors",
        ],
        "best_for": ["streetwear", "energy drinks", "tech accessories", "gaming"],
        "category": "mood",
    },
    {
        "key": "muted_understated",
        "name": "Muted Understated",
        "hex_colors": ["#A8A29E", "#D6D3D1", "#C2B8A3", "#9C9589", "#E7E5E4"],
        "prompt_keywords": [
            "muted understated greige tones",
            "quiet sophisticated neutral palette",
            "subdued elegant soft greys",
            "subtle refined desaturated warmth",
        ],
        "best_for": ["minimalist brands", "stationery", "architecture", "ceramics"],
        "category": "mood",
    },
    {
        "key": "pastel_gentle",
        "name": "Pastel Gentle",
        "hex_colors": ["#FFD1DC", "#AEC6CF", "#FDFD96", "#B39EB5", "#BAFFC9", "#FFB7B2"],
        "prompt_keywords": [
            "soft pastel candy palette",
            "gentle delicate baby colors",
            "light airy pastel rainbow",
            "sweet tender cotton-candy tones",
        ],
        "best_for": ["baby products", "dessert brands", "gifts", "party supplies"],
        "category": "mood",
    },
    {
        "key": "earth_organic",
        "name": "Earth Organic",
        "hex_colors": ["#6B4226", "#A0522D", "#8B7355", "#556B2F", "#C4A882"],
        "prompt_keywords": [
            "earthy organic natural brown tones",
            "rich soil and forest palette",
            "warm terra cotta olive warmth",
            "rustic natural earth pigments",
        ],
        "best_for": ["organic food", "natural cosmetics", "outdoor gear", "pottery"],
        "category": "mood",
    },
    {
        "key": "metallic_luxe",
        "name": "Metallic Luxe",
        "hex_colors": ["#D4AF37", "#C0C0C0", "#B87333", "#E5E4E2", "#CFB53B", "#8C7853"],
        "prompt_keywords": [
            "metallic gold silver bronze shimmer",
            "luxurious reflective precious metal tones",
            "opulent polished metallic palette",
            "gleaming champagne gold and platinum",
        ],
        "best_for": ["jewelry", "luxury packaging", "cosmetics", "watches", "awards"],
        "category": "mood",
    },
    {
        "key": "monochrome_bw",
        "name": "Monochrome Black & White",
        "hex_colors": ["#000000", "#333333", "#666666", "#999999", "#CCCCCC", "#FFFFFF"],
        "prompt_keywords": [
            "monochrome black and white palette",
            "grayscale tonal range",
            "achromatic noir high contrast",
            "pure black white grey composition",
        ],
        "best_for": ["fine art photography", "editorial", "luxury fashion", "watches"],
        "category": "mood",
    },
    {
        "key": "monochrome_sepia",
        "name": "Monochrome Sepia",
        "hex_colors": ["#704214", "#8B6914", "#C49E6C", "#E8D4B8", "#F5ECDF", "#5C3A1E"],
        "prompt_keywords": [
            "warm sepia vintage monochrome tones",
            "antique brown aged parchment palette",
            "nostalgic golden-brown warmth",
            "classic sepia-toned atmosphere",
        ],
        "best_for": ["heritage brands", "whiskey", "leather goods", "antiques"],
        "category": "mood",
    },
    {
        "key": "jewel_tones",
        "name": "Jewel Tones",
        "hex_colors": ["#0F5257", "#6B0848", "#2C1654", "#0A5C36", "#8B0000", "#1B1464"],
        "prompt_keywords": [
            "deep rich jewel-toned saturated colors",
            "emerald sapphire ruby amethyst palette",
            "opulent precious gemstone hues",
            "luxurious dark saturated jewel tones",
        ],
        "best_for": ["luxury fashion", "jewelry", "perfume", "wine", "home textiles"],
        "category": "mood",
    },
    {
        "key": "neon_pop",
        "name": "Neon Pop",
        "hex_colors": ["#FF1493", "#39FF14", "#FF6600", "#00FFFF", "#FFFF00"],
        "prompt_keywords": [
            "bright neon fluorescent pop colors",
            "electric glowing vivid neon palette",
            "bold cyberpunk neon-lit tones",
            "intense ultraviolet reactive colors",
        ],
        "best_for": ["nightlife", "gaming peripherals", "sportswear", "energy drinks"],
        "category": "mood",
    },
    {
        "key": "dusty_vintage",
        "name": "Dusty Vintage",
        "hex_colors": ["#C9B99A", "#A4907C", "#8A7968", "#D4C5A9", "#B5A28C", "#E8DFD0"],
        "prompt_keywords": [
            "dusty faded vintage muted tones",
            "aged worn patina palette",
            "retro desaturated warm haze",
            "weathered antique soft neutrals",
        ],
        "best_for": ["vintage clothing", "craft brands", "bookstores", "heritage"],
        "category": "mood",
    },
    {
        "key": "rich_saturated",
        "name": "Rich Saturated",
        "hex_colors": ["#FF0000", "#0000FF", "#FFD700", "#008000", "#800080"],
        "prompt_keywords": [
            "fully saturated rich primary colors",
            "bold vivid maximum chroma palette",
            "intense pure pigment tones",
            "deeply saturated vibrant hues",
        ],
        "best_for": ["toys", "fast food", "sports teams", "carnival", "packaging"],
        "category": "mood",
    },
    {
        "key": "desaturated_moody",
        "name": "Desaturated Moody",
        "hex_colors": ["#4A4E69", "#6B705C", "#7F7979", "#5C5470", "#3E4C59", "#565264"],
        "prompt_keywords": [
            "desaturated moody dark muted tones",
            "brooding subdued grey-infused palette",
            "atmospheric low-saturation palette",
            "somber quiet understated darkness",
        ],
        "best_for": ["indie fashion", "music albums", "dark spirits", "film noir"],
        "category": "mood",
    },
    {
        "key": "high_contrast",
        "name": "High Contrast",
        "hex_colors": ["#000000", "#FFFFFF", "#FF0000", "#FFFF00", "#0000FF"],
        "prompt_keywords": [
            "extreme high contrast bold palette",
            "stark black white with primary accents",
            "sharp graphic pop-art contrast",
            "dramatic maximum contrast composition",
        ],
        "best_for": ["graphic design", "poster art", "sportswear", "signage"],
        "category": "mood",
    },
    {
        "key": "candy_bright",
        "name": "Candy Bright",
        "hex_colors": ["#FF69B4", "#87CEEB", "#98FB98", "#FFB6C1", "#FFDAB9", "#E6E6FA"],
        "prompt_keywords": [
            "candy-colored bright sweet palette",
            "cheerful bubblegum pastel brights",
            "playful sugary confection tones",
            "joyful vibrant candy hues",
        ],
        "best_for": ["candy", "ice cream", "children products", "party", "toys"],
        "category": "mood",
    },
    {
        "key": "noir_shadows",
        "name": "Noir Shadows",
        "hex_colors": ["#0A0A0A", "#1C1C1C", "#2D2D2D", "#4A4A4A", "#C0C0C0"],
        "prompt_keywords": [
            "film noir deep shadow palette",
            "dark mysterious shadowy atmosphere",
            "noir black with silver accent highlights",
            "moody chiaroscuro darkness",
        ],
        "best_for": ["luxury spirits", "men grooming", "thriller books", "watches"],
        "category": "mood",
    },
    {
        "key": "romantic_blush",
        "name": "Romantic Blush",
        "hex_colors": ["#F4C2C2", "#E8A0BF", "#D4A5A5", "#F0D5CE", "#C9A9A6", "#F5E1DA"],
        "prompt_keywords": [
            "romantic blush rose pink palette",
            "soft feminine dusty rose tones",
            "tender warm blush and mauve",
            "delicate rosy love-inspired warmth",
        ],
        "best_for": ["bridal", "valentines", "perfume", "lingerie", "flowers"],
        "category": "mood",
    },
    {
        "key": "coastal_calm",
        "name": "Coastal Calm",
        "hex_colors": ["#B0C4DE", "#E0E8F0", "#87CEEB", "#F5F5DC", "#2F4F4F"],
        "prompt_keywords": [
            "coastal calm ocean blue-grey palette",
            "seaside tranquil muted blue tones",
            "serene beach driftwood colors",
            "peaceful shoreline soft palette",
        ],
        "best_for": ["resort wear", "home decor", "spa", "nautical brands"],
        "category": "mood",
    },
    {
        "key": "forest_deep",
        "name": "Forest Deep",
        "hex_colors": ["#1B4D3E", "#2E8B57", "#355E3B", "#228B22", "#013220", "#6B8E23"],
        "prompt_keywords": [
            "deep forest green lush palette",
            "rich emerald woodland tones",
            "dense verdant dark green atmosphere",
            "mossy enchanted forest colors",
        ],
        "best_for": ["outdoor brands", "organic products", "herbal tea", "wellness"],
        "category": "mood",
    },
    {
        "key": "sunset_gradient",
        "name": "Sunset Gradient",
        "hex_colors": ["#FF6B35", "#F7C59F", "#EFEFD0", "#004E89", "#1A659E", "#FF4E50"],
        "prompt_keywords": [
            "warm sunset gradient orange to blue",
            "golden hour sky transition palette",
            "fiery dusk horizon colors",
            "radiant sunset amber and indigo",
        ],
        "best_for": ["travel", "outdoor lifestyle", "beverages", "music festivals"],
        "category": "mood",
    },
    {
        "key": "zen_minimal",
        "name": "Zen Minimal",
        "hex_colors": ["#F5F5F0", "#E8E4DE", "#C4B9A8", "#8C8278", "#5C534A"],
        "prompt_keywords": [
            "zen minimalist warm neutral palette",
            "wabi-sabi subtle earth tones",
            "calm meditative muted beige",
            "tranquil Japanese-inspired simplicity",
        ],
        "best_for": ["wellness", "meditation apps", "tea brands", "skincare"],
        "category": "mood",
    },
    {
        "key": "retro_70s",
        "name": "Retro 70s",
        "hex_colors": ["#CB6015", "#E2A63B", "#704214", "#A0522D", "#F4A460", "#8B4513"],
        "prompt_keywords": [
            "retro 1970s warm brown orange palette",
            "vintage burnt sienna and mustard tones",
            "groovy earthy seventies warmth",
            "nostalgic amber and rust colors",
        ],
        "best_for": ["retro fashion", "craft beer", "vinyl records", "vintage decor"],
        "category": "mood",
    },

    # =========================================================================
    # INDUSTRY PALETTES (25)
    # =========================================================================

    {
        "key": "luxury_gold_black",
        "name": "Luxury Gold & Black",
        "hex_colors": ["#D4AF37", "#000000", "#1A1A1A", "#B8860B", "#F5E6CC"],
        "prompt_keywords": [
            "opulent gold on black luxury palette",
            "premium gilded dark elegance",
            "lavish black and gold high-end tones",
            "prestigious golden noir atmosphere",
        ],
        "best_for": ["luxury brands", "premium spirits", "high-end watches", "hotels"],
        "category": "industry",
    },
    {
        "key": "luxury_ivory_cream",
        "name": "Luxury Ivory & Cream",
        "hex_colors": ["#FFFFF0", "#FAF0E6", "#FFF8DC", "#FAEBD7", "#F5F5DC", "#EDE8D5"],
        "prompt_keywords": [
            "refined ivory cream luxury palette",
            "elegant warm white tonal subtlety",
            "sophisticated pearl and champagne tones",
            "timeless off-white understated luxury",
        ],
        "best_for": ["bridal", "luxury skincare", "fine linen", "premium stationery"],
        "category": "industry",
    },
    {
        "key": "beauty_pink_rose",
        "name": "Beauty Pink & Rose",
        "hex_colors": ["#FF69B4", "#DB7093", "#FFB6C1", "#FFC0CB", "#FF1493", "#C71585"],
        "prompt_keywords": [
            "beauty pink rose vibrant palette",
            "glamorous hot pink and fuchsia tones",
            "feminine bold rose cosmetics palette",
            "striking pink beauty-inspired colors",
        ],
        "best_for": ["cosmetics", "beauty tools", "lip products", "nail polish"],
        "category": "industry",
    },
    {
        "key": "beauty_nude_natural",
        "name": "Beauty Nude & Natural",
        "hex_colors": ["#E8C4A0", "#D2A679", "#C49E6C", "#F5DEB3", "#DEB887", "#BC8F8F"],
        "prompt_keywords": [
            "natural nude skin-tone beauty palette",
            "soft warm beige and tan tones",
            "organic neutral complexion shades",
            "subtle skin-flattering nude warmth",
        ],
        "best_for": ["foundation", "skincare", "body care", "nude fashion"],
        "category": "industry",
    },
    {
        "key": "fashion_bold_primary",
        "name": "Fashion Bold Primary",
        "hex_colors": ["#FF0000", "#0047AB", "#FFD700", "#FFFFFF", "#000000"],
        "prompt_keywords": [
            "bold primary color fashion palette",
            "striking red blue yellow contrast",
            "graphic high-fashion primary tones",
            "confident saturated editorial colors",
        ],
        "best_for": ["fashion editorial", "streetwear", "bold accessories", "pop art"],
        "category": "industry",
    },
    {
        "key": "fashion_muted_neutral",
        "name": "Fashion Muted Neutral",
        "hex_colors": ["#B5A999", "#9C8E7E", "#C4B7A6", "#A89F91", "#D5CFC6", "#8B8178"],
        "prompt_keywords": [
            "muted neutral fashion taupe palette",
            "sophisticated greige warm neutral tones",
            "quiet elegant mushroom and stone",
            "refined desaturated fashion neutrals",
        ],
        "best_for": ["luxury fashion", "knitwear", "handbags", "minimalist clothing"],
        "category": "industry",
    },
    {
        "key": "sport_energetic",
        "name": "Sport Energetic",
        "hex_colors": ["#FF4500", "#32CD32", "#00BFFF", "#FFD700", "#FF1493"],
        "prompt_keywords": [
            "energetic sport neon bright palette",
            "high-intensity athletic vivid colors",
            "dynamic performance bold accents",
            "powerful active sport tones",
        ],
        "best_for": ["athletic wear", "sports equipment", "fitness", "running shoes"],
        "category": "industry",
    },
    {
        "key": "sport_dark_power",
        "name": "Sport Dark Power",
        "hex_colors": ["#1A1A2E", "#16213E", "#0F3460", "#E94560", "#000000"],
        "prompt_keywords": [
            "dark power sport palette with red accent",
            "intense midnight athletic dark tones",
            "strong aggressive deep blue-black",
            "commanding dark sport authority",
        ],
        "best_for": ["combat sports", "gym equipment", "protein supplements", "motorsport"],
        "category": "industry",
    },
    {
        "key": "food_warm_appetizing",
        "name": "Food Warm Appetizing",
        "hex_colors": ["#CD5C5C", "#DAA520", "#8B4513", "#FF6347", "#FFDAB9", "#F4A460"],
        "prompt_keywords": [
            "warm appetizing food palette",
            "rich tomato red and golden brown",
            "inviting savory warm tones",
            "delicious hearty food-inspired warmth",
        ],
        "best_for": ["restaurants", "food packaging", "cookbooks", "sauces", "bakery"],
        "category": "industry",
    },
    {
        "key": "food_fresh_green",
        "name": "Food Fresh Green",
        "hex_colors": ["#228B22", "#32CD32", "#90EE90", "#F0FFF0", "#ADFF2F", "#006400"],
        "prompt_keywords": [
            "fresh green healthy food palette",
            "crisp leafy vibrant green tones",
            "organic clean natural produce colors",
            "garden-fresh verdant bright palette",
        ],
        "best_for": ["salads", "health food", "juice bars", "vegan products", "herbs"],
        "category": "industry",
    },
    {
        "key": "auto_metallic_dark",
        "name": "Auto Metallic Dark",
        "hex_colors": ["#2C3E50", "#1A1A2E", "#4A4A4A", "#7F8C8D", "#C0C0C0", "#2F4F4F"],
        "prompt_keywords": [
            "automotive dark metallic palette",
            "sleek gunmetal and carbon tones",
            "polished dark chrome atmosphere",
            "premium vehicle matte-dark finish",
        ],
        "best_for": ["automotive", "motorcycles", "car accessories", "tires"],
        "category": "industry",
    },
    {
        "key": "auto_racing_red",
        "name": "Auto Racing Red",
        "hex_colors": ["#CC0000", "#1A1A1A", "#FFFFFF", "#FFD700", "#8B0000"],
        "prompt_keywords": [
            "racing red and black automotive palette",
            "high-speed bold Ferrari red tones",
            "aggressive sport car red and gold",
            "intense motorsport crimson palette",
        ],
        "best_for": ["sports cars", "racing gear", "automotive accessories", "helmets"],
        "category": "industry",
    },
    {
        "key": "tech_blue_modern",
        "name": "Tech Blue Modern",
        "hex_colors": ["#0078D4", "#00BCF2", "#E8F4FD", "#002050", "#FFFFFF"],
        "prompt_keywords": [
            "modern tech blue corporate palette",
            "clean digital blue and white tones",
            "professional technology blue gradient",
            "sleek contemporary blue-forward palette",
        ],
        "best_for": ["software", "SaaS", "cloud services", "electronics", "fintech"],
        "category": "industry",
    },
    {
        "key": "tech_dark_minimal",
        "name": "Tech Dark Minimal",
        "hex_colors": ["#121212", "#1E1E1E", "#2D2D2D", "#00FF88", "#FFFFFF"],
        "prompt_keywords": [
            "dark minimal tech UI palette",
            "sleek developer dark-mode tones",
            "minimal black with green accent",
            "sophisticated dark interface palette",
        ],
        "best_for": ["dev tools", "gaming hardware", "cybersecurity", "crypto"],
        "category": "industry",
    },
    {
        "key": "travel_tropical",
        "name": "Travel Tropical",
        "hex_colors": ["#00CED1", "#FF6F61", "#FFD700", "#228B22", "#FF4500", "#40E0D0"],
        "prompt_keywords": [
            "tropical travel vibrant island palette",
            "turquoise coral and palm-green tones",
            "exotic paradise beach colors",
            "lush warm tropical vacation hues",
        ],
        "best_for": ["travel agencies", "resort brands", "swimwear", "surfing"],
        "category": "industry",
    },
    {
        "key": "travel_earth_adventure",
        "name": "Travel Earth Adventure",
        "hex_colors": ["#8B4513", "#556B2F", "#DAA520", "#D2691E", "#6B8E23"],
        "prompt_keywords": [
            "earthy adventure travel palette",
            "rugged outdoor khaki and brown tones",
            "expedition warm natural earth colors",
            "wilderness trail dusty warm palette",
        ],
        "best_for": ["outdoor travel", "hiking gear", "safari", "camping", "adventure"],
        "category": "industry",
    },
    {
        "key": "real_estate_warm_home",
        "name": "Real Estate Warm Home",
        "hex_colors": ["#F5F0E8", "#D4C5A9", "#A0926E", "#8B7D6B", "#E8DFD0", "#C9B99A"],
        "prompt_keywords": [
            "warm inviting home interior palette",
            "cozy residential beige and linen",
            "welcoming domestic neutral warmth",
            "comfortable lived-in soft neutrals",
        ],
        "best_for": ["real estate", "home staging", "furniture", "interior design"],
        "category": "industry",
    },
    {
        "key": "jewelry_precious_metals",
        "name": "Jewelry Precious Metals",
        "hex_colors": ["#FFD700", "#C0C0C0", "#E5E4E2", "#B87333", "#F5F5DC", "#1A1A1A"],
        "prompt_keywords": [
            "precious metal gold silver platinum palette",
            "luxurious gleaming jewelry tones",
            "opulent metallic shine and brilliance",
            "elegant precious metal warmth and luster",
        ],
        "best_for": ["fine jewelry", "watches", "luxury accessories", "wedding bands"],
        "category": "industry",
    },
    {
        "key": "fragrance_purple_mystique",
        "name": "Fragrance Purple Mystique",
        "hex_colors": ["#4B0082", "#800080", "#9932CC", "#DDA0DD", "#E6E6FA", "#2E0854"],
        "prompt_keywords": [
            "mystical purple fragrance palette",
            "deep violet and amethyst tones",
            "sensual dark purple mystique",
            "enchanting plum and lavender atmosphere",
        ],
        "best_for": ["perfume", "cologne", "scented candles", "aromatherapy"],
        "category": "industry",
    },
    {
        "key": "fragrance_fresh_aquatic",
        "name": "Fragrance Fresh Aquatic",
        "hex_colors": ["#00B4D8", "#90E0EF", "#CAF0F8", "#0077B6", "#ADE8F4", "#FFFFFF"],
        "prompt_keywords": [
            "fresh aquatic ocean blue palette",
            "cool crisp water-inspired tones",
            "clean marine blue-green freshness",
            "breezy coastal aquatic atmosphere",
        ],
        "best_for": ["men fragrance", "deodorant", "body wash", "fresh scents"],
        "category": "industry",
    },
    {
        "key": "wellness_spa",
        "name": "Wellness Spa",
        "hex_colors": ["#A8D5BA", "#D4E8D0", "#F0F7F4", "#7FB185", "#E8F5E9", "#B2DFDB"],
        "prompt_keywords": [
            "calming spa green wellness palette",
            "soothing sage and eucalyptus tones",
            "tranquil mint and seafoam serenity",
            "refreshing herbal spa atmosphere",
        ],
        "best_for": ["spa products", "wellness", "yoga", "essential oils", "massage"],
        "category": "industry",
    },
    {
        "key": "coffee_shop",
        "name": "Coffee Shop",
        "hex_colors": ["#6F4E37", "#3C2415", "#A0522D", "#D2B48C", "#F5DEB3", "#FFFDD0"],
        "prompt_keywords": [
            "rich coffee brown warm palette",
            "roasted espresso and cream tones",
            "warm artisan cafe brown palette",
            "inviting barista mocha and latte",
        ],
        "best_for": ["coffee brands", "cafes", "chocolate", "bakeries", "tea"],
        "category": "industry",
    },
    {
        "key": "pharma_clinical",
        "name": "Pharma Clinical",
        "hex_colors": ["#FFFFFF", "#E8F4FD", "#0077C2", "#00A651", "#F2F2F2"],
        "prompt_keywords": [
            "clinical pharmaceutical blue-white palette",
            "clean sterile medical tones",
            "trustworthy healthcare blue and green",
            "professional pharma clean palette",
        ],
        "best_for": ["pharmaceuticals", "health tech", "medical devices", "clinics"],
        "category": "industry",
    },
    {
        "key": "kids_playful",
        "name": "Kids Playful",
        "hex_colors": ["#FF6B6B", "#4ECDC4", "#FFE66D", "#95E1D3", "#F38181", "#AA96DA"],
        "prompt_keywords": [
            "playful bright kids color palette",
            "cheerful primary rainbow tones",
            "fun whimsical children vibrant colors",
            "joyful colorful cartoon-inspired palette",
        ],
        "best_for": ["children toys", "kids clothing", "school supplies", "games"],
        "category": "industry",
    },
    {
        "key": "fintech_trust",
        "name": "Fintech Trust",
        "hex_colors": ["#003366", "#005B96", "#6497B1", "#B3CDE0", "#FFFFFF"],
        "prompt_keywords": [
            "trustworthy fintech navy blue palette",
            "professional corporate deep blue tones",
            "reliable banking blue gradient",
            "authoritative financial dark blue palette",
        ],
        "best_for": ["banking", "fintech", "insurance", "investment", "accounting"],
        "category": "industry",
    },

    # =========================================================================
    # SEASON PALETTES (16)
    # =========================================================================

    {
        "key": "spring_bloom",
        "name": "Spring Bloom",
        "hex_colors": ["#FF69B4", "#98FB98", "#FFD700", "#DDA0DD", "#F0E68C", "#90EE90"],
        "prompt_keywords": [
            "blooming spring floral vibrant palette",
            "fresh garden flower bright colors",
            "lively petal and leaf spring tones",
            "blossoming warm springtime hues",
        ],
        "best_for": ["floral brands", "garden products", "spring fashion", "weddings"],
        "category": "season",
    },
    {
        "key": "spring_pastel",
        "name": "Spring Pastel",
        "hex_colors": ["#FFB7C5", "#B5EAD7", "#C7CEEA", "#FFDAC1", "#E2F0CB", "#F0E6EF"],
        "prompt_keywords": [
            "soft spring pastel delicate palette",
            "gentle blush mint lavender tones",
            "light airy spring pastel colors",
            "tender pastel renewal palette",
        ],
        "best_for": ["Easter products", "baby showers", "spring decor", "stationery"],
        "category": "season",
    },
    {
        "key": "summer_vibrant",
        "name": "Summer Vibrant",
        "hex_colors": ["#FF6347", "#00CED1", "#FFD700", "#FF4500", "#00FA9A"],
        "prompt_keywords": [
            "vibrant summer bold saturated palette",
            "hot sun-drenched vivid colors",
            "bright beach-party summer tones",
            "intense radiant summer energy",
        ],
        "best_for": ["summer fashion", "sunglasses", "sunscreen", "pool accessories"],
        "category": "season",
    },
    {
        "key": "summer_tropical",
        "name": "Summer Tropical",
        "hex_colors": ["#FF1493", "#00FF7F", "#FFD700", "#FF6347", "#40E0D0", "#FF8C00"],
        "prompt_keywords": [
            "tropical summer exotic color palette",
            "lush flamingo pink and palm green",
            "vivid island paradise summer tones",
            "hot tropical fruit-inspired colors",
        ],
        "best_for": ["tropical prints", "rum brands", "exotic fruit", "resort wear"],
        "category": "season",
    },
    {
        "key": "autumn_warm",
        "name": "Autumn Warm",
        "hex_colors": ["#D2691E", "#CD853F", "#B8860B", "#8B4513", "#F4A460", "#A0522D"],
        "prompt_keywords": [
            "warm autumn brown and amber palette",
            "rich fall foliage earthy tones",
            "cozy golden-brown harvest warmth",
            "deep cinnamon and caramel autumn",
        ],
        "best_for": ["fall fashion", "pumpkin spice", "cozy home", "knits"],
        "category": "season",
    },
    {
        "key": "autumn_harvest",
        "name": "Autumn Harvest",
        "hex_colors": ["#CC5500", "#FFD700", "#8B0000", "#DAA520", "#556B2F", "#B22222"],
        "prompt_keywords": [
            "autumn harvest orange red gold palette",
            "rich pumpkin and cranberry tones",
            "bountiful fall harvest colors",
            "vibrant deep autumn foliage palette",
        ],
        "best_for": ["thanksgiving", "seasonal food", "cider brands", "fall decor"],
        "category": "season",
    },
    {
        "key": "winter_cool",
        "name": "Winter Cool",
        "hex_colors": ["#B0E0E6", "#E0FFFF", "#F0F8FF", "#4682B4", "#708090", "#FFFFFF"],
        "prompt_keywords": [
            "cool winter icy blue-white palette",
            "frosty crystalline pale blue tones",
            "crisp cold winter steel and ice",
            "pristine frozen winter atmosphere",
        ],
        "best_for": ["winter skincare", "ski gear", "cold beverages", "winter fashion"],
        "category": "season",
    },
    {
        "key": "winter_holiday",
        "name": "Winter Holiday",
        "hex_colors": ["#C0C0C0", "#B0E0E6", "#FFFFFF", "#FFD700", "#ADD8E6", "#E6E6FA"],
        "prompt_keywords": [
            "winter holiday silver and gold palette",
            "festive frosty sparkle tones",
            "elegant winter wonderland palette",
            "magical snowy holiday atmosphere",
        ],
        "best_for": ["holiday gifts", "winter decor", "ski resorts", "new year"],
        "category": "season",
    },
    {
        "key": "holiday_christmas",
        "name": "Holiday Christmas",
        "hex_colors": ["#C41E3A", "#006400", "#FFD700", "#FFFFFF", "#8B0000", "#228B22"],
        "prompt_keywords": [
            "classic Christmas red green gold palette",
            "traditional festive holiday colors",
            "merry Christmas deep red and pine green",
            "joyful holiday celebration tones",
        ],
        "best_for": ["christmas products", "holiday packaging", "gift wrap", "ornaments"],
        "category": "season",
    },
    {
        "key": "holiday_valentines",
        "name": "Holiday Valentine's",
        "hex_colors": ["#FF0000", "#FF69B4", "#FFC0CB", "#FFFFFF", "#8B0000", "#FFB6C1"],
        "prompt_keywords": [
            "Valentine red pink romantic palette",
            "passionate love heart colors",
            "romantic deep red and soft pink",
            "tender Valentine's Day tones",
        ],
        "best_for": ["valentines gifts", "chocolate boxes", "greeting cards", "flowers"],
        "category": "season",
    },
    {
        "key": "holiday_halloween",
        "name": "Holiday Halloween",
        "hex_colors": ["#FF6600", "#000000", "#800080", "#1A1A1A", "#39FF14", "#FFD700"],
        "prompt_keywords": [
            "Halloween orange black purple palette",
            "spooky dark neon-green accent tones",
            "eerie midnight and pumpkin orange",
            "haunted dramatic Halloween colors",
        ],
        "best_for": ["halloween costumes", "candy", "party decorations", "horror"],
        "category": "season",
    },
    {
        "key": "year_round_neutral",
        "name": "Year Round Neutral",
        "hex_colors": ["#F5F5F5", "#D3D3D3", "#A9A9A9", "#696969", "#808080", "#C0C0C0"],
        "prompt_keywords": [
            "timeless year-round neutral grey palette",
            "versatile all-season grey tones",
            "evergreen balanced neutral colors",
            "universal adaptable grey palette",
        ],
        "best_for": ["basics", "office wear", "everyday accessories", "appliances"],
        "category": "season",
    },
    {
        "key": "spring_cherry_blossom",
        "name": "Spring Cherry Blossom",
        "hex_colors": ["#FFB7C5", "#FF8FAB", "#FADADD", "#F5F0F0", "#C9929A", "#FFFFFF"],
        "prompt_keywords": [
            "cherry blossom soft pink palette",
            "delicate sakura petal tones",
            "Japanese spring blossom atmosphere",
            "ethereal pink and white floral",
        ],
        "best_for": ["Japanese brands", "spring cosmetics", "tea", "floral designs"],
        "category": "season",
    },
    {
        "key": "summer_coastal",
        "name": "Summer Coastal",
        "hex_colors": ["#1E90FF", "#F5F5DC", "#FFFFFF", "#87CEEB", "#FFD700", "#00CED1"],
        "prompt_keywords": [
            "bright coastal summer blue palette",
            "sunny beach sky-blue and sand",
            "ocean breeze nautical summer tones",
            "crisp blue and white seaside",
        ],
        "best_for": ["nautical fashion", "beach accessories", "surfwear", "seafood"],
        "category": "season",
    },
    {
        "key": "autumn_moody",
        "name": "Autumn Moody",
        "hex_colors": ["#4A3728", "#6B4226", "#8B6914", "#2F4F4F", "#5C4033", "#3C2415"],
        "prompt_keywords": [
            "moody dark autumn palette",
            "brooding deep brown and forest tones",
            "atmospheric foggy autumn darkness",
            "rich somber late-autumn colors",
        ],
        "best_for": ["dark fashion", "leather goods", "whiskey", "gothic style"],
        "category": "season",
    },
    {
        "key": "winter_nordic",
        "name": "Winter Nordic",
        "hex_colors": ["#E8E8E8", "#B0C4DE", "#2F4F4F", "#8B0000", "#F5F5F5", "#696969"],
        "prompt_keywords": [
            "Nordic winter muted blue-grey palette",
            "Scandinavian cool minimalist tones",
            "hygge cozy dark green and warm red",
            "crisp Nordic frost atmosphere",
        ],
        "best_for": ["Scandinavian design", "wool products", "winter home", "candles"],
        "category": "season",
    },

    # =========================================================================
    # TIME OF DAY PALETTES (16)
    # =========================================================================

    {
        "key": "dawn_pink",
        "name": "Dawn Pink",
        "hex_colors": ["#FFB6C1", "#FFC0CB", "#E6E6FA", "#B0C4DE", "#FAEBD7", "#F0E6EF"],
        "prompt_keywords": [
            "soft dawn pink and lavender palette",
            "gentle first light rosy tones",
            "delicate early morning pastel glow",
            "tender pink sunrise atmosphere",
        ],
        "best_for": ["skincare", "wellness", "yoga", "morning routine products"],
        "category": "time_of_day",
    },
    {
        "key": "morning_fresh",
        "name": "Morning Fresh",
        "hex_colors": ["#87CEEB", "#FFFFF0", "#90EE90", "#F0FFFF", "#FFD700", "#E0FFFF"],
        "prompt_keywords": [
            "fresh bright morning light palette",
            "crisp clear early-day tones",
            "clean invigorating morning colors",
            "bright optimistic daybreak atmosphere",
        ],
        "best_for": ["breakfast brands", "juice", "toothpaste", "morning supplements"],
        "category": "time_of_day",
    },
    {
        "key": "golden_hour_warm",
        "name": "Golden Hour Warm",
        "hex_colors": ["#DAA520", "#CD853F", "#FFD700", "#F4A460", "#FF8C00", "#FFF8DC"],
        "prompt_keywords": [
            "warm golden hour amber sunset palette",
            "rich honey and amber magic-hour light",
            "luminous golden late-afternoon glow",
            "radiant warm sunset golden tones",
        ],
        "best_for": ["lifestyle brands", "outdoor products", "wine", "photography"],
        "category": "time_of_day",
    },
    {
        "key": "noon_bright",
        "name": "Noon Bright",
        "hex_colors": ["#FFFFFF", "#00BFFF", "#FFD700", "#32CD32", "#FF6347"],
        "prompt_keywords": [
            "bright midday high-key palette",
            "vivid noon full-sun colors",
            "crisp overexposed daylight tones",
            "sharp saturated noon atmosphere",
        ],
        "best_for": ["outdoor sports", "summer products", "food trucks", "sunglasses"],
        "category": "time_of_day",
    },
    {
        "key": "afternoon_soft",
        "name": "Afternoon Soft",
        "hex_colors": ["#F5DEB3", "#DEB887", "#D2B48C", "#FAEBD7", "#FFE4C4", "#FFDEAD"],
        "prompt_keywords": [
            "soft warm afternoon light palette",
            "gentle late-afternoon wheat tones",
            "relaxed mellow afternoon glow",
            "easy warm diffused daylight",
        ],
        "best_for": ["home decor", "baked goods", "tea brands", "linen products"],
        "category": "time_of_day",
    },
    {
        "key": "blue_hour_twilight",
        "name": "Blue Hour Twilight",
        "hex_colors": ["#191970", "#4169E1", "#6A5ACD", "#483D8B", "#7B68EE", "#E6E6FA"],
        "prompt_keywords": [
            "blue hour twilight deep palette",
            "dusky violet-blue transition tones",
            "cool ethereal twilight atmosphere",
            "mysterious blue-purple evening sky",
        ],
        "best_for": ["nightlife", "perfume", "evening wear", "cocktail bars"],
        "category": "time_of_day",
    },
    {
        "key": "dusk_amber",
        "name": "Dusk Amber",
        "hex_colors": ["#FF8C00", "#FF6347", "#8B4513", "#2F2F2F", "#DAA520", "#4A2D0A"],
        "prompt_keywords": [
            "warm dusk amber and burnt orange palette",
            "fiery sunset horizon dark transition",
            "rich dusky orange fading to dark",
            "smoldering amber twilight tones",
        ],
        "best_for": ["spirits", "campfire brands", "western wear", "outdoor dining"],
        "category": "time_of_day",
    },
    {
        "key": "night_dark",
        "name": "Night Dark",
        "hex_colors": ["#0A0A0A", "#1A1A2E", "#16213E", "#0F3460", "#000000"],
        "prompt_keywords": [
            "deep dark night palette",
            "inky midnight blue-black tones",
            "atmospheric nocturnal darkness",
            "dense velvety night atmosphere",
        ],
        "best_for": ["luxury spirits", "nightclub brands", "men cologne", "dark fashion"],
        "category": "time_of_day",
    },
    {
        "key": "night_neon",
        "name": "Night Neon",
        "hex_colors": ["#0A0A0A", "#FF1493", "#00FFFF", "#FF6600", "#39FF14", "#1A1A1A"],
        "prompt_keywords": [
            "neon-lit dark night palette",
            "vibrant glowing neon on black",
            "electric cyberpunk night colors",
            "bold fluorescent nightlife tones",
        ],
        "best_for": ["nightlife", "gaming", "EDM brands", "neon signs", "cyberpunk"],
        "category": "time_of_day",
    },
    {
        "key": "night_moonlit",
        "name": "Night Moonlit",
        "hex_colors": ["#1A1A2E", "#C0C0C0", "#4682B4", "#2F4F4F", "#B0C4DE", "#E8E8E8"],
        "prompt_keywords": [
            "moonlit night silver blue palette",
            "cool lunar glow soft tones",
            "ethereal moonlight shimmer",
            "serene silvery night atmosphere",
        ],
        "best_for": ["night cream", "sleep products", "lunar jewelry", "romance novels"],
        "category": "time_of_day",
    },
    {
        "key": "overcast_grey",
        "name": "Overcast Grey",
        "hex_colors": ["#808080", "#A9A9A9", "#C0C0C0", "#D3D3D3", "#696969", "#B8B8B8"],
        "prompt_keywords": [
            "overcast grey muted cloudy palette",
            "diffused soft grey daylight tones",
            "flat neutral overcast atmosphere",
            "cool subdued cloud-cover palette",
        ],
        "best_for": ["minimalist brands", "concrete products", "urban fashion"],
        "category": "time_of_day",
    },
    {
        "key": "stormy_dramatic",
        "name": "Stormy Dramatic",
        "hex_colors": ["#2F4F4F", "#1C1C1C", "#4A4A4A", "#708090", "#363636", "#556B2F"],
        "prompt_keywords": [
            "stormy dramatic dark grey-green palette",
            "tempestuous brooding thundercloud tones",
            "intense atmospheric storm colors",
            "powerful turbulent moody darkness",
        ],
        "best_for": ["adventure gear", "rugged menswear", "thrillers", "dark spirits"],
        "category": "time_of_day",
    },
    {
        "key": "sunrise_golden",
        "name": "Sunrise Golden",
        "hex_colors": ["#FF7F50", "#FFD700", "#FF6347", "#FFA07A", "#FFDAB9", "#FFF8DC"],
        "prompt_keywords": [
            "golden sunrise warm coral palette",
            "radiant early morning sun tones",
            "vibrant peachy golden dawn",
            "warm luminous sunrise glow",
        ],
        "best_for": ["breakfast cereals", "orange juice", "morning coffee", "vitamins"],
        "category": "time_of_day",
    },
    {
        "key": "late_afternoon_haze",
        "name": "Late Afternoon Haze",
        "hex_colors": ["#E8C4A0", "#C49E6C", "#D4A574", "#B8956A", "#F0DCC8", "#A08060"],
        "prompt_keywords": [
            "hazy late afternoon warm palette",
            "diffused golden hour dusty tones",
            "languid warm afternoon atmosphere",
            "soft sepia-tinted lazy daylight",
        ],
        "best_for": ["lifestyle photography", "linen brands", "iced tea", "resort"],
        "category": "time_of_day",
    },
    {
        "key": "midnight_velvet",
        "name": "Midnight Velvet",
        "hex_colors": ["#0D0221", "#150535", "#190640", "#2D1B69", "#0A0118", "#E6E6FA"],
        "prompt_keywords": [
            "deep midnight velvet purple-black palette",
            "luxurious dark indigo night tones",
            "sumptuous midnight sky depth",
            "opulent dark velvet atmosphere",
        ],
        "best_for": ["luxury lingerie", "premium spirits", "velvet fashion", "perfume"],
        "category": "time_of_day",
    },
    {
        "key": "pre_dawn_blue",
        "name": "Pre-Dawn Blue",
        "hex_colors": ["#1A1A3E", "#2E2E5E", "#4A4A7E", "#8080A0", "#B0B0C8", "#D0D0E0"],
        "prompt_keywords": [
            "pre-dawn deep blue gradient palette",
            "early morning dark-to-light blue",
            "quiet predawn cool blue tones",
            "still dark awakening blue atmosphere",
        ],
        "best_for": ["alarm clocks", "early bird products", "running gear", "coffee"],
        "category": "time_of_day",
    },

    # =========================================================================
    # ADDITIONAL PALETTES (20+)
    # =========================================================================

    {
        "key": "vaporwave_retro",
        "name": "Vaporwave Retro",
        "hex_colors": ["#FF71CE", "#01CDFE", "#05FFA1", "#B967FF", "#FFFB96"],
        "prompt_keywords": [
            "vaporwave retro neon pastel palette",
            "synthwave pink and cyan tones",
            "nostalgic digital 80s aesthetic",
            "dreamy retrowave gradient colors",
        ],
        "best_for": ["retro gaming", "streetwear", "music albums", "digital art"],
        "category": "mood",
    },
    {
        "key": "art_deco",
        "name": "Art Deco",
        "hex_colors": ["#D4AF37", "#1A1A2E", "#007065", "#C0C0C0", "#F5F5DC", "#2C3E50"],
        "prompt_keywords": [
            "art deco gold teal and dark palette",
            "glamorous 1920s geometric luxury",
            "opulent Gatsby-era gold and jade",
            "elegant deco metallic and jewel tones",
        ],
        "best_for": ["luxury hotels", "cocktail bars", "premium packaging", "jewelry"],
        "category": "mood",
    },
    {
        "key": "scandinavian_light",
        "name": "Scandinavian Light",
        "hex_colors": ["#FFFFFF", "#F5F5F0", "#E8E4DE", "#D5CCC5", "#A0968C"],
        "prompt_keywords": [
            "bright Scandinavian white minimal palette",
            "clean Nordic light airy tones",
            "crisp hygge warm-white atmosphere",
            "simple Scandinavian natural light",
        ],
        "best_for": ["furniture", "home goods", "minimal fashion", "ceramics"],
        "category": "mood",
    },
    {
        "key": "mediterranean_sun",
        "name": "Mediterranean Sun",
        "hex_colors": ["#0047AB", "#FFFFFF", "#FF6347", "#FFD700", "#228B22", "#E8C4A0"],
        "prompt_keywords": [
            "Mediterranean sun-drenched blue and white",
            "warm Tuscan terracotta and cobalt",
            "bright coastal Italian palette",
            "vibrant Greek island blue and gold",
        ],
        "best_for": ["olive oil", "ceramics", "travel brands", "Mediterranean food"],
        "category": "mood",
    },
    {
        "key": "industrial_raw",
        "name": "Industrial Raw",
        "hex_colors": ["#4A4A4A", "#8B8B8B", "#B87333", "#696969", "#2F2F2F", "#C0C0C0"],
        "prompt_keywords": [
            "raw industrial concrete and steel palette",
            "rugged exposed metal and copper tones",
            "urban factory dark grey atmosphere",
            "gritty industrial warehouse colors",
        ],
        "best_for": ["craft tools", "industrial design", "loft decor", "brewing"],
        "category": "industry",
    },
    {
        "key": "botanical_garden",
        "name": "Botanical Garden",
        "hex_colors": ["#2E8B57", "#98FB98", "#006400", "#9ACD32", "#F0FFF0", "#556B2F"],
        "prompt_keywords": [
            "lush botanical garden green palette",
            "verdant plant-filled greenhouse tones",
            "rich tropical foliage colors",
            "fresh leafy botanical atmosphere",
        ],
        "best_for": ["plant shops", "botanical skincare", "herbal supplements", "tea"],
        "category": "industry",
    },
    {
        "key": "desert_sand",
        "name": "Desert Sand",
        "hex_colors": ["#EDC9AF", "#C2B280", "#DEB887", "#D2691E", "#F5DEB3", "#8B7355"],
        "prompt_keywords": [
            "warm desert sand dune palette",
            "arid golden beige and tan tones",
            "sun-baked sandstone warmth",
            "dry dusty desert landscape colors",
        ],
        "best_for": ["sunscreen", "desert fashion", "adventure travel", "southwestern"],
        "category": "mood",
    },
    {
        "key": "ocean_deep",
        "name": "Ocean Deep",
        "hex_colors": ["#000080", "#006994", "#004953", "#0077B6", "#00B4D8", "#023E8A"],
        "prompt_keywords": [
            "deep ocean dark blue-green palette",
            "abyssal marine deep-sea tones",
            "rich navy and teal ocean depths",
            "mysterious underwater blue atmosphere",
        ],
        "best_for": ["marine brands", "sailing", "seafood", "diving equipment"],
        "category": "mood",
    },
    {
        "key": "lavender_fields",
        "name": "Lavender Fields",
        "hex_colors": ["#E6E6FA", "#9370DB", "#B19CD9", "#D8BFD8", "#DDA0DD", "#F0E6F6"],
        "prompt_keywords": [
            "soft lavender purple field palette",
            "gentle violet and mauve tones",
            "calming lavender herbal atmosphere",
            "dreamy purple floral palette",
        ],
        "best_for": ["lavender products", "aromatherapy", "sleep aids", "bath bombs"],
        "category": "mood",
    },
    {
        "key": "cherry_red",
        "name": "Cherry Red",
        "hex_colors": ["#DC143C", "#8B0000", "#FF0000", "#B22222", "#FFFFFF", "#1A1A1A"],
        "prompt_keywords": [
            "bold cherry red dominant palette",
            "striking crimson and scarlet tones",
            "passionate intense red atmosphere",
            "powerful deep red on black and white",
        ],
        "best_for": ["lipstick", "sports cars", "energy brands", "valentines"],
        "category": "mood",
    },
    {
        "key": "sage_terracotta",
        "name": "Sage & Terracotta",
        "hex_colors": ["#9CAF88", "#CC7751", "#B8A088", "#D4C5A9", "#7A8B6F", "#E8C4A0"],
        "prompt_keywords": [
            "sage green and terracotta warm palette",
            "natural earthy clay and herb tones",
            "organic Mediterranean earth palette",
            "grounded warm botanical neutrals",
        ],
        "best_for": ["home decor", "pottery", "plant accessories", "natural beauty"],
        "category": "mood",
    },
    {
        "key": "ice_cream_parlor",
        "name": "Ice Cream Parlor",
        "hex_colors": ["#F8D7E8", "#A8E6CF", "#DCEDC1", "#FFD3B6", "#FFAAA5", "#FFF5BA"],
        "prompt_keywords": [
            "sweet ice cream pastel palette",
            "delicious sorbet soft colors",
            "creamy dessert parlor tones",
            "light whimsical gelato palette",
        ],
        "best_for": ["ice cream", "frozen yogurt", "candy shops", "dessert brands"],
        "category": "industry",
    },
    {
        "key": "wine_cellar",
        "name": "Wine Cellar",
        "hex_colors": ["#722F37", "#4A0E0E", "#2C1608", "#8B4513", "#C9B99A", "#1A0A0A"],
        "prompt_keywords": [
            "deep wine cellar burgundy palette",
            "rich merlot and oak barrel tones",
            "dark aged wood and red wine",
            "sumptuous vineyard deep red-brown",
        ],
        "best_for": ["wine brands", "fine dining", "cigar lounges", "dark chocolate"],
        "category": "industry",
    },
    {
        "key": "tropical_fruit",
        "name": "Tropical Fruit",
        "hex_colors": ["#FF6B6B", "#FFA62F", "#FFE66D", "#06D6A0", "#FF1493", "#FF8C42"],
        "prompt_keywords": [
            "tropical fruit vibrant palette",
            "juicy mango papaya passion fruit colors",
            "bright exotic fruity warm tones",
            "lush fresh tropical produce palette",
        ],
        "best_for": ["smoothie brands", "tropical beverages", "fruit snacks", "juice"],
        "category": "industry",
    },
    {
        "key": "eco_sustainable",
        "name": "Eco Sustainable",
        "hex_colors": ["#2D5016", "#8FBC8F", "#F5F5DC", "#DAA520", "#90A955", "#C4A882"],
        "prompt_keywords": [
            "eco sustainable natural green palette",
            "organic earth-friendly muted tones",
            "green recycled kraft paper colors",
            "environmentally conscious natural palette",
        ],
        "best_for": ["eco brands", "recycled products", "sustainable fashion", "hemp"],
        "category": "industry",
    },
    {
        "key": "galaxy_cosmic",
        "name": "Galaxy Cosmic",
        "hex_colors": ["#0D0221", "#3A0CA3", "#7209B7", "#F72585", "#4CC9F0", "#000000"],
        "prompt_keywords": [
            "cosmic galaxy deep space palette",
            "nebula purple blue and pink tones",
            "stellar interstellar dark colors",
            "vast mysterious cosmic atmosphere",
        ],
        "best_for": ["sci-fi products", "space-themed items", "astrology", "EDM"],
        "category": "mood",
    },
    {
        "key": "ballet_pink",
        "name": "Ballet Pink",
        "hex_colors": ["#F4C2C2", "#FADADD", "#F5E6E0", "#E8B4B8", "#FFF0F5", "#D4A5A5"],
        "prompt_keywords": [
            "delicate ballet pink satin palette",
            "soft blush pointe-shoe tones",
            "graceful feminine pale pink",
            "tender gentle ballerina atmosphere",
        ],
        "best_for": ["ballet brands", "feminine fashion", "bridal", "beauty"],
        "category": "mood",
    },
    {
        "key": "urban_graffiti",
        "name": "Urban Graffiti",
        "hex_colors": ["#FF1493", "#00FF00", "#FF6600", "#0000FF", "#FFFF00", "#1A1A1A"],
        "prompt_keywords": [
            "urban graffiti bold spray-paint palette",
            "street art vibrant raw colors",
            "edgy rebellious bright graffiti tones",
            "gritty urban mural neon on dark",
        ],
        "best_for": ["streetwear", "sneakers", "skate brands", "urban culture"],
        "category": "mood",
    },
    {
        "key": "rose_gold_blush",
        "name": "Rose Gold Blush",
        "hex_colors": ["#B76E79", "#E8C4C4", "#F0D5CE", "#D4A5A5", "#F5E1DA", "#C9A9A6"],
        "prompt_keywords": [
            "rose gold metallic blush palette",
            "warm pink-gold shimmer tones",
            "elegant feminine rose-gold atmosphere",
            "soft copper-pink luxurious warmth",
        ],
        "best_for": ["cosmetics", "bridal accessories", "tech accessories", "jewelry"],
        "category": "industry",
    },
    {
        "key": "matcha_green",
        "name": "Matcha Green",
        "hex_colors": ["#7B8B3A", "#A4BE7B", "#D5E8B5", "#E8F0DE", "#5C6B2F", "#F0F5E8"],
        "prompt_keywords": [
            "matcha green organic tea palette",
            "earthy Japanese green tones",
            "fresh powdered matcha atmosphere",
            "natural warm green zen palette",
        ],
        "best_for": ["matcha brands", "health food", "Japanese products", "tea shops"],
        "category": "industry",
    },
    {
        "key": "rustic_farmhouse",
        "name": "Rustic Farmhouse",
        "hex_colors": ["#8B7355", "#D2B48C", "#F5F5DC", "#556B2F", "#A0522D", "#FFFFFF"],
        "prompt_keywords": [
            "rustic farmhouse wood and linen palette",
            "warm country barn natural tones",
            "cozy rural homestead colors",
            "charming vintage farmhouse atmosphere",
        ],
        "best_for": ["artisan food", "farm-to-table", "country decor", "preserves"],
        "category": "mood",
    },
    {
        "key": "cyber_punk",
        "name": "Cyberpunk",
        "hex_colors": ["#FF003C", "#00FFFF", "#FF00FF", "#0A0A0A", "#1A1A2E", "#FFFF00"],
        "prompt_keywords": [
            "cyberpunk neon on dark palette",
            "futuristic magenta cyan electric tones",
            "dystopian high-tech neon glow",
            "intense digital cyberpunk atmosphere",
        ],
        "best_for": ["gaming accessories", "VR products", "sci-fi merch", "tech gear"],
        "category": "mood",
    },
    {
        "key": "tuscan_villa",
        "name": "Tuscan Villa",
        "hex_colors": ["#CC7751", "#DAA520", "#556B2F", "#DEB887", "#8B4513", "#F5E6CC"],
        "prompt_keywords": [
            "warm Tuscan villa terracotta palette",
            "Italian countryside golden tones",
            "sun-baked Mediterranean warmth",
            "rustic Tuscany olive and clay",
        ],
        "best_for": ["Italian food", "olive oil", "terracotta pots", "wine"],
        "category": "mood",
    },
    {
        "key": "bubblegum_pop",
        "name": "Bubblegum Pop",
        "hex_colors": ["#FF69B4", "#FF1493", "#DA70D6", "#87CEEB", "#FFFFFF", "#FFD700"],
        "prompt_keywords": [
            "bubblegum pop pink and blue palette",
            "fun girly bright pop tones",
            "playful hot pink glam colors",
            "energetic Y2K pop-culture palette",
        ],
        "best_for": ["teen fashion", "lip gloss", "pop music merch", "phone cases"],
        "category": "mood",
    },
    {
        "key": "moss_stone",
        "name": "Moss & Stone",
        "hex_colors": ["#6B705C", "#A5A58D", "#B7B7A4", "#D4C5A9", "#3E4A34", "#C4B99A"],
        "prompt_keywords": [
            "organic moss and stone neutral palette",
            "muted sage olive and granite tones",
            "quiet natural woodland colors",
            "subdued earthy moss green and warm grey",
        ],
        "best_for": ["organic brands", "stone jewelry", "garden tools", "natural decor"],
        "category": "mood",
    },
]

PALETTE_BY_KEY = {p["key"]: p for p in COLOR_PALETTES}
