"""
Composition rules for professional photography and image generation prompts.

Provides a comprehensive library of 45+ compositional techniques with exact
prompt keywords optimized for Gemini and SDXL models. Each rule includes
usage guidance, industry recommendations, and ready-to-use prompt phrases.

Usage:
    from knowledge.prompt_templates.composition_rules import COMPOSITION_RULES, COMPOSITION_BY_KEY

    rule = COMPOSITION_BY_KEY["rule_of_thirds"]
    keywords = rule["prompt_keywords"]
"""

COMPOSITION_RULES = [
    {
        "key": "rule_of_thirds",
        "name": "Rule of Thirds",
        "description": "Divides the frame into a 3x3 grid and places the subject at one of the four intersection points. Creates natural visual balance and guides the viewer's eye.",
        "prompt_keywords": [
            "rule of thirds composition",
            "subject placed at power point intersection",
            "off-center subject placement",
            "balanced negative space around subject",
            "grid-aligned focal point",
            "asymmetric visual balance",
        ],
        "when_to_use": "Default go-to composition for most subjects. Works especially well when the subject needs breathing room or when you want a natural, editorial feel.",
        "industries": ["lifestyle", "portrait", "landscape", "editorial", "real_estate", "travel"],
    },
    {
        "key": "golden_ratio",
        "name": "Golden Ratio",
        "description": "Uses the 1:1.618 proportion to create harmonious, naturally pleasing arrangements. Produces a more refined and organic feel than the rule of thirds.",
        "prompt_keywords": [
            "golden ratio composition",
            "phi proportion framing",
            "harmonious natural proportions",
            "fibonacci placement of subject",
            "mathematically balanced composition",
            "classical proportional harmony",
        ],
        "when_to_use": "Ideal for luxury and fine-art imagery where elegance and timelessness matter. Use when the subject deserves a sense of classical beauty.",
        "industries": ["luxury", "fine_art", "beauty", "jewelry", "editorial", "architecture"],
    },
    {
        "key": "golden_spiral",
        "name": "Golden Spiral",
        "description": "Arranges elements along a logarithmic spiral based on the Fibonacci sequence. Draws the viewer's eye along a natural curving path toward the focal point.",
        "prompt_keywords": [
            "golden spiral composition",
            "fibonacci spiral visual flow",
            "logarithmic curve leading to subject",
            "spiraling visual path",
            "organic swirl composition",
            "nautilus shell visual flow",
        ],
        "when_to_use": "Best for images with flowing or organic elements such as floral arrangements, food plating, or curving landscapes.",
        "industries": ["food", "floral", "fine_art", "beauty", "landscape", "editorial"],
    },
    {
        "key": "centered_symmetry",
        "name": "Centered Symmetry",
        "description": "Places the subject dead center with mirror-like balance on both sides. Conveys power, authority, confidence, and direct engagement with the viewer.",
        "prompt_keywords": [
            "centered symmetrical composition",
            "subject directly centered in frame",
            "mirror balance left and right",
            "powerful direct frontal framing",
            "symmetrical arrangement",
            "perfectly balanced center placement",
        ],
        "when_to_use": "Use for hero product shots, powerful portraits, or any subject that demands undivided attention and authority.",
        "industries": ["beauty", "product", "luxury", "fashion", "automotive", "tech"],
    },
    {
        "key": "diagonal_dominance",
        "name": "Diagonal Dominance",
        "description": "Tilts the primary visual elements along a diagonal axis to inject energy, movement, and dynamism. Breaks static horizontal-vertical monotony.",
        "prompt_keywords": [
            "diagonal composition",
            "dynamic diagonal lines through frame",
            "tilted visual elements creating energy",
            "diagonal leading movement",
            "angular dynamic arrangement",
            "diagonal visual tension",
        ],
        "when_to_use": "Ideal for action, sports, fashion, and automotive imagery where you want to convey speed, energy, or edginess.",
        "industries": ["sport", "fashion", "automotive", "action", "music", "streetwear"],
    },
    {
        "key": "leading_lines",
        "name": "Leading Lines",
        "description": "Uses natural or man-made lines in the scene to draw the viewer's eye toward the main subject. Creates depth and a strong sense of direction.",
        "prompt_keywords": [
            "leading lines composition",
            "converging lines drawing eye to subject",
            "perspective lines guiding viewer",
            "linear depth and direction",
            "road or path leading to focal point",
            "architectural lines as visual guides",
        ],
        "when_to_use": "Works best in environments with strong linear elements like roads, hallways, fences, or architectural features.",
        "industries": ["architecture", "automotive", "travel", "real_estate", "fashion", "landscape"],
    },
    {
        "key": "frame_within_frame",
        "name": "Frame Within a Frame",
        "description": "Uses elements in the scene such as doorways, windows, arches, or foliage to create a secondary frame around the subject. Adds depth and context.",
        "prompt_keywords": [
            "frame within frame composition",
            "subject framed by doorway or arch",
            "natural framing element around subject",
            "window framing the scene",
            "nested frame creating depth",
            "environmental frame enclosing subject",
        ],
        "when_to_use": "Use when the environment offers natural framing elements. Adds layers of storytelling and draws attention inward.",
        "industries": ["portrait", "architecture", "travel", "real_estate", "wedding", "editorial"],
    },
    {
        "key": "negative_space_left",
        "name": "Negative Space Left",
        "description": "Positions the subject on the right side of the frame with large empty space on the left. Creates room for text overlays or a sense of openness.",
        "prompt_keywords": [
            "negative space on the left side",
            "subject positioned right of frame",
            "large empty area left side",
            "open space to the left for text",
            "breathing room left of subject",
            "copy space on left side of image",
        ],
        "when_to_use": "Perfect for advertising layouts where text or headlines need to be placed on the left side of the image.",
        "industries": ["advertising", "editorial", "luxury", "tech", "beauty", "social_media"],
    },
    {
        "key": "negative_space_right",
        "name": "Negative Space Right",
        "description": "Positions the subject on the left side with expansive empty space to the right. Ideal for layouts requiring right-aligned copy or logos.",
        "prompt_keywords": [
            "negative space on the right side",
            "subject positioned left of frame",
            "large empty area right side",
            "open space to the right for text",
            "breathing room right of subject",
            "copy space on right side of image",
        ],
        "when_to_use": "Use for advertising or social media where text, CTAs, or branding elements go on the right side.",
        "industries": ["advertising", "editorial", "luxury", "social_media", "tech", "beauty"],
    },
    {
        "key": "negative_space_top",
        "name": "Negative Space Top",
        "description": "Places the subject in the lower portion of the frame with empty space above. Creates a feeling of aspiration, sky, or vertical breathing room.",
        "prompt_keywords": [
            "negative space above subject",
            "subject low in frame",
            "large empty area at top of image",
            "open sky or ceiling above subject",
            "vertical breathing room above",
            "copy space at top of frame",
        ],
        "when_to_use": "Best for images that need a headline or title at the top, or when you want the subject to feel grounded.",
        "industries": ["advertising", "editorial", "landscape", "travel", "social_media"],
    },
    {
        "key": "negative_space_bottom",
        "name": "Negative Space Bottom",
        "description": "Places the subject in the upper portion with empty space below. Provides room for captions, subtitles, or a sense of floating elevation.",
        "prompt_keywords": [
            "negative space below subject",
            "subject high in frame",
            "large empty area at bottom of image",
            "ground or floor area below subject",
            "vertical space beneath",
            "copy space at bottom of frame",
        ],
        "when_to_use": "Useful for layouts needing bottom text, captions, or when the subject should feel elevated or suspended.",
        "industries": ["advertising", "editorial", "social_media", "product", "luxury"],
    },
    {
        "key": "dutch_angle",
        "name": "Dutch Angle",
        "description": "Tilts the entire camera on its roll axis to create a disorienting, dramatic, or edgy perspective. Conveys unease, tension, or creative flair.",
        "prompt_keywords": [
            "Dutch angle tilted camera",
            "canted frame creating visual tension",
            "oblique tilted perspective",
            "dramatic camera tilt",
            "angled horizon line",
            "off-kilter disorienting framing",
        ],
        "when_to_use": "Use sparingly for dramatic editorial, music, horror, or avant-garde fashion to create a sense of unease or creative energy.",
        "industries": ["fashion", "music", "editorial", "film", "streetwear", "art"],
    },
    {
        "key": "low_angle_power",
        "name": "Low Angle Power Shot",
        "description": "Camera positioned below the subject looking upward. Makes the subject appear dominant, heroic, powerful, and larger than life.",
        "prompt_keywords": [
            "low angle looking up at subject",
            "heroic powerful perspective from below",
            "subject towering above camera",
            "worm's eye upward angle",
            "imposing low camera position",
            "dramatic upward perspective",
        ],
        "when_to_use": "Use for athletes, vehicles, buildings, or any subject that should feel powerful and commanding.",
        "industries": ["sport", "automotive", "fashion", "architecture", "luxury", "fitness"],
    },
    {
        "key": "high_angle_vulnerability",
        "name": "High Angle Vulnerability",
        "description": "Camera positioned above the subject looking down. Makes the subject appear smaller, vulnerable, or provides an omniscient overview perspective.",
        "prompt_keywords": [
            "high angle looking down at subject",
            "overhead perspective creating vulnerability",
            "subject appears small from above",
            "elevated camera position",
            "diminishing downward angle",
            "bird's eye perspective on subject",
        ],
        "when_to_use": "Use when you want the subject to appear delicate, introspective, or when showing spatial context from above.",
        "industries": ["editorial", "fashion", "portrait", "food", "art", "film"],
    },
    {
        "key": "eye_level_intimate",
        "name": "Eye Level Intimate",
        "description": "Camera placed at the subject's eye level creating a direct, honest, and personal connection. Feels natural and relatable to the viewer.",
        "prompt_keywords": [
            "eye level camera angle",
            "direct gaze at camera level",
            "intimate personal perspective",
            "natural eye-to-eye framing",
            "relatable straight-on angle",
            "honest direct camera position",
        ],
        "when_to_use": "Default for portraits and lifestyle imagery. Creates empathy, trust, and a personal connection with the viewer.",
        "industries": ["portrait", "lifestyle", "beauty", "fashion", "healthcare", "corporate"],
    },
    {
        "key": "worms_eye_view",
        "name": "Worm's Eye View",
        "description": "Camera placed at ground level looking straight up. Creates extreme drama and an unusual perspective that makes ordinary subjects extraordinary.",
        "prompt_keywords": [
            "worm's eye view from ground level",
            "extreme low angle looking straight up",
            "camera on ground shooting upward",
            "dramatic floor-level perspective",
            "towering subject above camera",
            "ground-up extreme perspective",
        ],
        "when_to_use": "Use for dramatic architectural shots, towering trees, or creative perspectives that transform everyday scenes.",
        "industries": ["architecture", "automotive", "fashion", "art", "travel", "sport"],
    },
    {
        "key": "birds_eye_view",
        "name": "Bird's Eye View",
        "description": "Camera positioned directly above the scene looking straight down. Reveals patterns, layouts, and spatial relationships not visible from other angles.",
        "prompt_keywords": [
            "bird's eye view directly overhead",
            "top-down aerial perspective",
            "looking straight down from above",
            "overhead drone perspective",
            "plan view from directly above",
            "aerial top-down composition",
        ],
        "when_to_use": "Ideal for revealing patterns, food arrangements, flat lays, or urban landscapes where the overhead view tells a story.",
        "industries": ["food", "travel", "real_estate", "landscape", "product", "editorial"],
    },
    {
        "key": "flat_lay_overhead",
        "name": "Flat Lay Overhead",
        "description": "Objects arranged on a flat surface and photographed from directly above. Creates organized, curated, graphic compositions popular on social media.",
        "prompt_keywords": [
            "flat lay overhead composition",
            "objects arranged on surface shot from above",
            "curated top-down product arrangement",
            "knolling style organized layout",
            "styled flat lay photography",
            "items neatly arranged viewed from above",
            "graphic overhead still life",
        ],
        "when_to_use": "Perfect for product collections, recipe ingredients, outfit layouts, tech accessories, or any curated grouping.",
        "industries": ["food", "fashion", "beauty", "tech", "lifestyle", "social_media", "product"],
    },
    {
        "key": "over_the_shoulder",
        "name": "Over the Shoulder",
        "description": "Camera positioned behind one person looking over their shoulder toward the main subject. Creates intimacy, context, and a voyeuristic storytelling perspective.",
        "prompt_keywords": [
            "over the shoulder perspective",
            "looking past foreground person at subject",
            "shoulder-framed point of view",
            "second-person storytelling angle",
            "intimate observer perspective",
            "foreground shoulder framing subject",
        ],
        "when_to_use": "Use for conversational scenes, product demonstrations, or when showing someone's point of view adds narrative depth.",
        "industries": ["film", "editorial", "lifestyle", "corporate", "tech", "gaming"],
    },
    {
        "key": "close_up_fill_frame",
        "name": "Close Up Fill Frame",
        "description": "Subject fills the entire frame edge to edge with no background visible. Maximizes detail, texture, and emotional impact.",
        "prompt_keywords": [
            "close up filling entire frame",
            "subject edge to edge no background",
            "tight crop maximum detail",
            "frame-filling close-up shot",
            "intimate detail filling composition",
            "no negative space all subject",
        ],
        "when_to_use": "Use for beauty close-ups, texture studies, emotional portraits, or when every detail of the subject matters.",
        "industries": ["beauty", "food", "product", "portrait", "macro", "jewelry"],
    },
    {
        "key": "medium_shot",
        "name": "Medium Shot",
        "description": "Frames the subject from roughly the waist up, balancing subject detail with environmental context. The workhorse framing of commercial photography.",
        "prompt_keywords": [
            "medium shot waist-up framing",
            "half-body composition",
            "subject with surrounding context",
            "balanced detail and environment",
            "commercial medium framing",
            "torso-up natural framing",
        ],
        "when_to_use": "Default for fashion, lifestyle, and corporate imagery. Balances personal connection with context.",
        "industries": ["fashion", "corporate", "lifestyle", "portrait", "e-commerce", "editorial"],
    },
    {
        "key": "wide_establishing",
        "name": "Wide Establishing Shot",
        "description": "Shows the full scene with the subject small within a larger environment. Establishes location, mood, and context before closer views.",
        "prompt_keywords": [
            "wide establishing shot",
            "full scene environmental context",
            "subject small in vast setting",
            "location-setting wide angle",
            "expansive scene with figure",
            "environmental wide composition",
        ],
        "when_to_use": "Use to introduce a location, show scale, or when the environment is as important as the subject.",
        "industries": ["travel", "real_estate", "landscape", "architecture", "film", "editorial"],
    },
    {
        "key": "extreme_close_up",
        "name": "Extreme Close Up",
        "description": "Isolates a tiny detail such as an eye, texture, or component. Reveals beauty in the micro scale and creates abstract, graphic compositions.",
        "prompt_keywords": [
            "extreme close-up macro detail",
            "isolated micro detail shot",
            "single feature filling frame",
            "abstract detail close-up",
            "macro-level intimate detail",
            "hyper-detailed single element",
        ],
        "when_to_use": "Use for beauty eye shots, jewelry details, texture studies, or when revealing hidden details tells the story.",
        "industries": ["beauty", "jewelry", "food", "product", "art", "science"],
    },
    {
        "key": "extreme_wide",
        "name": "Extreme Wide Shot",
        "description": "Captures a vast panoramic scene where the subject is tiny or absent. Emphasizes scale, landscape, and the grandeur of the environment.",
        "prompt_keywords": [
            "extreme wide panoramic shot",
            "vast landscape tiny subject",
            "epic scale wide composition",
            "panoramic environmental view",
            "sweeping vista composition",
            "grand scale wide angle",
        ],
        "when_to_use": "Use for epic landscapes, architectural showcases, or when conveying the vastness and scale of an environment.",
        "industries": ["travel", "landscape", "architecture", "real_estate", "automotive", "outdoor"],
    },
    {
        "key": "pattern_repetition",
        "name": "Pattern and Repetition",
        "description": "Fills the frame with repeating visual elements to create rhythm, texture, and graphic impact. One broken pattern element can serve as the focal point.",
        "prompt_keywords": [
            "pattern repetition composition",
            "repeating visual elements filling frame",
            "rhythmic pattern creating texture",
            "graphic repetitive arrangement",
            "visual rhythm through repetition",
            "uniform pattern with focal break",
        ],
        "when_to_use": "Use for architectural details, product lineups, food arrays, or whenever visual rhythm and graphic impact are desired.",
        "industries": ["architecture", "fashion", "food", "product", "art", "interior_design"],
    },
    {
        "key": "juxtaposition_contrast",
        "name": "Juxtaposition and Contrast",
        "description": "Places contrasting elements side by side to create tension, storytelling, or visual surprise. Can contrast size, color, texture, old vs new, etc.",
        "prompt_keywords": [
            "juxtaposition of contrasting elements",
            "visual contrast side by side",
            "opposing elements creating tension",
            "unexpected pairing composition",
            "contrast between old and new",
            "dramatic visual contradiction",
        ],
        "when_to_use": "Use for editorial storytelling, conceptual campaigns, or when highlighting differences makes the message stronger.",
        "industries": ["editorial", "fashion", "art", "advertising", "conceptual", "social_impact"],
    },
    {
        "key": "depth_layering",
        "name": "Depth Layering",
        "description": "Creates distinct foreground, midground, and background layers to build three-dimensional depth. Each layer adds context and visual richness.",
        "prompt_keywords": [
            "layered depth composition",
            "distinct foreground midground background",
            "three-dimensional depth layers",
            "stacked visual planes",
            "depth through overlapping elements",
            "multi-layer spatial composition",
        ],
        "when_to_use": "Use for landscapes, environmental portraits, or any scene where creating a sense of depth and dimension is important.",
        "industries": ["landscape", "travel", "portrait", "real_estate", "editorial", "film"],
    },
    {
        "key": "foreground_interest",
        "name": "Foreground Interest",
        "description": "Places a compelling element in the near foreground to anchor the composition and create depth. The foreground element leads the eye into the scene.",
        "prompt_keywords": [
            "strong foreground element",
            "compelling near-camera object",
            "foreground anchor creating depth",
            "close element leading into scene",
            "depth through foreground interest",
            "near-field object framing background",
        ],
        "when_to_use": "Excellent for landscapes, travel, and real estate where an interesting foreground element adds dimension and scale.",
        "industries": ["landscape", "travel", "real_estate", "food", "editorial", "architecture"],
    },
    {
        "key": "l_shaped_composition",
        "name": "L-Shaped Composition",
        "description": "Arranges elements along two edges of the frame forming an L shape, leaving the opposite corner open. Creates stability with visual interest.",
        "prompt_keywords": [
            "L-shaped compositional arrangement",
            "elements along two adjoining edges",
            "corner-weighted composition",
            "L-frame visual structure",
            "two-edge anchored arrangement",
            "asymmetric L-shaped layout",
        ],
        "when_to_use": "Use for still life, product groupings, or interior scenes where an L-shaped arrangement feels natural and grounded.",
        "industries": ["product", "interior_design", "food", "still_life", "editorial"],
    },
    {
        "key": "s_curve",
        "name": "S-Curve Composition",
        "description": "A flowing S-shaped line meanders through the frame creating elegance, grace, and a natural visual journey. Mimics rivers, roads, and the human form.",
        "prompt_keywords": [
            "S-curve composition",
            "flowing sinuous line through frame",
            "elegant S-shaped visual path",
            "meandering curve leading eye",
            "serpentine flowing composition",
            "graceful winding visual journey",
        ],
        "when_to_use": "Ideal for winding roads, rivers, fashion poses, or any scene with natural curves that guide the eye through the frame.",
        "industries": ["landscape", "fashion", "automotive", "food", "travel", "beauty"],
    },
    {
        "key": "triangle_composition",
        "name": "Triangle Composition",
        "description": "Arranges key elements to form a triangular shape within the frame. Creates visual stability, hierarchy, and a solid structural foundation.",
        "prompt_keywords": [
            "triangular composition",
            "three-point visual structure",
            "pyramid arrangement of elements",
            "stable triangle formation",
            "three-element balanced grouping",
            "geometric triangle layout",
        ],
        "when_to_use": "Use for group portraits, product trios, food plating, or whenever three elements need a stable and visually appealing arrangement.",
        "industries": ["product", "portrait", "food", "editorial", "still_life", "fashion"],
    },
    {
        "key": "radial_composition",
        "name": "Radial Composition",
        "description": "Elements radiate outward from or converge toward a central point like spokes of a wheel. Creates explosive energy or focused intensity.",
        "prompt_keywords": [
            "radial composition from center point",
            "elements radiating outward",
            "spoke-like visual arrangement",
            "converging lines to central focus",
            "starburst radial pattern",
            "centrifugal visual energy",
        ],
        "when_to_use": "Use for architectural domes, flower close-ups, circular food plating, or any scene with a strong central point of radiation.",
        "industries": ["architecture", "food", "art", "product", "floral", "editorial"],
    },
    {
        "key": "rule_of_odds",
        "name": "Rule of Odds",
        "description": "Uses an odd number of subjects (3, 5, 7) to create a more natural and visually pleasing grouping. Even numbers feel static; odds feel dynamic.",
        "prompt_keywords": [
            "odd number of subjects grouped",
            "three or five element arrangement",
            "rule of odds visual grouping",
            "asymmetric odd-numbered collection",
            "natural odd grouping composition",
            "three subjects in balanced arrangement",
        ],
        "when_to_use": "Use when arranging multiple objects or subjects. Three is the most common and powerful grouping number.",
        "industries": ["food", "product", "still_life", "editorial", "floral", "interior_design"],
    },
    {
        "key": "color_blocking",
        "name": "Color Blocking",
        "description": "Divides the frame into large areas of solid, contrasting colors. Creates bold graphic impact and a modern, fashion-forward aesthetic.",
        "prompt_keywords": [
            "color blocking composition",
            "bold solid color areas contrasting",
            "graphic color field division",
            "large blocks of contrasting color",
            "Mondrian-style color segmentation",
            "vibrant color area composition",
        ],
        "when_to_use": "Use for fashion editorials, pop-art inspired campaigns, or any image where bold color contrast is the primary design element.",
        "industries": ["fashion", "beauty", "advertising", "art", "editorial", "social_media"],
    },
    {
        "key": "vanishing_point",
        "name": "Vanishing Point",
        "description": "All perspective lines converge at a single vanishing point creating extreme depth and a powerful pull into the image. Strong sense of infinity.",
        "prompt_keywords": [
            "single vanishing point perspective",
            "converging lines to infinity point",
            "one-point perspective composition",
            "deep perspective tunnel effect",
            "lines meeting at distant focal point",
            "infinite depth vanishing point",
        ],
        "when_to_use": "Use for hallways, roads, tunnels, architectural interiors, or any scene with strong one-point perspective.",
        "industries": ["architecture", "automotive", "travel", "real_estate", "film", "editorial"],
    },
    {
        "key": "horizon_placement_high",
        "name": "High Horizon Placement",
        "description": "Places the horizon line in the upper third of the frame, emphasizing the foreground and ground-level details. Creates a grounded, intimate feel.",
        "prompt_keywords": [
            "high horizon line in upper third",
            "emphasis on foreground and ground",
            "horizon near top of frame",
            "ground-dominant landscape composition",
            "low sky high foreground",
            "earth-heavy horizon placement",
        ],
        "when_to_use": "Use when the foreground or ground plane is more interesting than the sky, such as fields of flowers or textured terrain.",
        "industries": ["landscape", "travel", "agriculture", "outdoor", "editorial"],
    },
    {
        "key": "horizon_placement_low",
        "name": "Low Horizon Placement",
        "description": "Places the horizon line in the lower third of the frame, emphasizing sky, clouds, or vertical elements. Creates a sense of openness and grandeur.",
        "prompt_keywords": [
            "low horizon line in lower third",
            "emphasis on sky and atmosphere",
            "horizon near bottom of frame",
            "sky-dominant landscape composition",
            "expansive sky above low horizon",
            "heavens-heavy horizon placement",
        ],
        "when_to_use": "Use for dramatic skies, sunsets, cloud formations, or when the sky is the star of the composition.",
        "industries": ["landscape", "travel", "outdoor", "real_estate", "editorial", "automotive"],
    },
    {
        "key": "minimalist_single_subject",
        "name": "Minimalist Single Subject",
        "description": "Strips the image to its absolute essence: one subject, vast clean space, no distractions. Achieves maximum impact through extreme simplicity.",
        "prompt_keywords": [
            "minimalist single subject composition",
            "one subject vast empty space",
            "extreme simplicity clean background",
            "reduction to visual essence",
            "isolated subject minimal environment",
            "clean uncluttered single element",
        ],
        "when_to_use": "Use for luxury products, tech devices, beauty hero shots, or any subject that needs to command attention without competition.",
        "industries": ["luxury", "tech", "beauty", "product", "fashion", "automotive"],
    },
    {
        "key": "dynamic_tension",
        "name": "Dynamic Tension",
        "description": "Creates visual conflict by placing elements that pull the eye in opposing directions. Generates energy, unease, and emotional engagement.",
        "prompt_keywords": [
            "dynamic tension opposing forces",
            "visual conflict between elements",
            "competing focal points",
            "push-pull visual energy",
            "tension between opposing directions",
            "unresolved visual forces in frame",
        ],
        "when_to_use": "Use for dramatic editorial, conceptual art, or campaigns that want to provoke thought and emotional engagement.",
        "industries": ["editorial", "art", "fashion", "advertising", "conceptual", "film"],
    },
    {
        "key": "visual_weight_balance",
        "name": "Visual Weight Balance",
        "description": "Balances elements of different sizes by placing larger elements near the center and smaller ones toward edges, or using color and tone to equalize weight.",
        "prompt_keywords": [
            "visual weight balanced composition",
            "asymmetric balance through visual mass",
            "weighted equilibrium of elements",
            "balanced arrangement by size and tone",
            "counterbalanced visual elements",
            "harmonious weight distribution",
        ],
        "when_to_use": "Use when composing scenes with multiple elements of varying sizes. Ensures the image feels stable without rigid symmetry.",
        "industries": ["product", "editorial", "still_life", "interior_design", "food", "fashion"],
    },
    # --- Additional creative compositions ---
    {
        "key": "split_screen",
        "name": "Split Screen Diptych",
        "description": "Divides the frame into two distinct halves, each showing a different subject, moment, or perspective. Creates narrative comparison or before-after storytelling.",
        "prompt_keywords": [
            "split screen diptych composition",
            "two halves divided frame",
            "side by side comparison layout",
            "dual panel visual narrative",
            "bisected frame two scenes",
            "left-right split composition",
        ],
        "when_to_use": "Use for before-and-after comparisons, dual product showcases, or narrative contrast between two states or perspectives.",
        "industries": ["advertising", "beauty", "editorial", "product", "fitness", "social_media"],
    },
    {
        "key": "selective_focus_bokeh",
        "name": "Selective Focus with Bokeh",
        "description": "Uses extreme shallow depth of field to isolate the subject with a creamy blurred background. The bokeh itself becomes a compositional and aesthetic element.",
        "prompt_keywords": [
            "selective focus shallow depth of field",
            "creamy bokeh background blur",
            "sharp subject blurred surroundings",
            "f/1.4 wide aperture isolation",
            "dreamy out-of-focus background",
            "subject isolation through bokeh",
        ],
        "when_to_use": "Use for portraits, product hero shots, or any subject that needs to pop from a distracting background.",
        "industries": ["portrait", "product", "beauty", "wedding", "food", "lifestyle"],
    },
    {
        "key": "reflected_composition",
        "name": "Reflected Composition",
        "description": "Uses reflections in water, glass, mirrors, or polished surfaces to create a doubled or mirrored image. Adds symmetry, depth, and visual poetry.",
        "prompt_keywords": [
            "reflected composition in water or mirror",
            "mirror reflection doubling the subject",
            "symmetrical reflection creating depth",
            "water surface reflection composition",
            "mirrored image visual poetry",
            "reflective surface doubled framing",
        ],
        "when_to_use": "Use near bodies of water, glass facades, polished floors, or any reflective surface that doubles the visual interest.",
        "industries": ["landscape", "architecture", "fashion", "beauty", "travel", "art"],
    },
    {
        "key": "silhouette_composition",
        "name": "Silhouette Composition",
        "description": "Subject rendered as a dark shape against a bright background, stripping away detail to emphasize form, outline, and mood.",
        "prompt_keywords": [
            "silhouette against bright background",
            "dark figure backlit outline",
            "shape-defined subject no detail",
            "dramatic silhouette composition",
            "backlit form and contour only",
            "high contrast shadow figure",
        ],
        "when_to_use": "Use during golden hour, against sunsets, or with strong backlighting to create mood, mystery, and graphic simplicity.",
        "industries": ["travel", "fitness", "editorial", "film", "outdoor", "music"],
    },
    {
        "key": "layered_transparency",
        "name": "Layered Transparency",
        "description": "Overlaps semi-transparent elements like glass, fabric, smoke, or water to create ethereal depth and visual complexity through see-through layers.",
        "prompt_keywords": [
            "layered transparent elements overlapping",
            "see-through material creating depth",
            "semi-transparent overlapping layers",
            "ethereal layered transparency",
            "sheer materials stacked in depth",
            "translucent layering composition",
        ],
        "when_to_use": "Use for beauty campaigns, fragrance imagery, or artistic compositions where layers of transparency add mystery and sophistication.",
        "industries": ["beauty", "fashion", "fragrance", "art", "luxury", "editorial"],
    },
]

COMPOSITION_BY_KEY = {rule["key"]: rule for rule in COMPOSITION_RULES}
