"""
Texture and material definitions for photorealistic image generation prompts.

Provides a comprehensive library of 90+ material descriptions with exact prompt
keywords optimized for photorealistic rendering in Gemini and SDXL models. Each
material includes lighting recommendations for achieving the most convincing results.

Usage:
    from knowledge.prompt_templates.texture_materials import TEXTURE_MATERIALS, MATERIAL_BY_KEY

    material = MATERIAL_BY_KEY["gold"]
    keywords = material["prompt_keywords"]
    lighting = material["lighting_tips"]
"""

TEXTURE_MATERIALS = [
    # =====================================================================
    # GLASS
    # =====================================================================
    {
        "key": "transparent_glass",
        "material": "Transparent Glass",
        "category": "glass",
        "description": "Crystal clear glass with visible refraction, clean edges, and subtle reflections that reveal objects behind and within.",
        "prompt_keywords": [
            "clear transparent glass",
            "visible light refraction through glass",
            "clean sharp glass edges",
            "subtle specular reflections on surface",
            "see-through glass material",
            "pristine optical clarity",
        ],
        "lighting_tips": "Use strong backlighting to emphasize transparency. Add a small key light to create specular highlights on edges. Avoid flat frontal lighting which kills the see-through effect.",
    },
    {
        "key": "frosted_glass",
        "material": "Frosted Glass",
        "category": "glass",
        "description": "Translucent glass with a soft diffused surface that scatters light and obscures details while maintaining a luminous glow.",
        "prompt_keywords": [
            "frosted translucent glass surface",
            "soft diffused light through glass",
            "matte sandblasted glass texture",
            "privacy glass light scattering",
            "luminous frosted material",
            "etched glass soft glow",
        ],
        "lighting_tips": "Backlight strongly to create a soft ethereal glow. Side lighting reveals the frosted texture. Keep backgrounds simple as they will be blurred through the glass.",
    },
    {
        "key": "colored_glass",
        "material": "Colored Glass",
        "category": "glass",
        "description": "Richly tinted glass that transmits saturated color when light passes through, reminiscent of stained glass or decorative bottles.",
        "prompt_keywords": [
            "colored tinted glass",
            "saturated light glowing through glass",
            "stained glass rich color",
            "jewel-toned transparent material",
            "colored glass light transmission",
            "vibrant tinted glass surface",
        ],
        "lighting_tips": "Backlight to make colors glow intensely. Place on a white surface to show colored shadows and caustics. Vary light angle to shift color saturation.",
    },
    {
        "key": "crystal_glass",
        "material": "Crystal Glass",
        "category": "glass",
        "description": "Brilliant lead crystal with precision-cut facets that split light into prismatic rainbows and create dazzling specular highlights.",
        "prompt_keywords": [
            "crystal glass brilliant facets",
            "prismatic light refraction rainbow",
            "cut crystal sparkling surface",
            "lead crystal luxury drinkware",
            "faceted crystal catching light",
            "diamond-cut crystal clarity",
        ],
        "lighting_tips": "Use a single hard point light to maximize prismatic reflections. Dark background makes facets sparkle. Slight backlight creates rainbow caustics on the surface below.",
    },
    # =====================================================================
    # METAL
    # =====================================================================
    {
        "key": "gold",
        "material": "Polished Gold",
        "category": "metal",
        "description": "Warm, lustrous 24-karat gold with rich yellow reflections and luxurious specular highlights that convey opulence.",
        "prompt_keywords": [
            "polished gold surface",
            "warm 24K gold reflections",
            "rich golden luster and sheen",
            "luxurious gold specular highlights",
            "gleaming gold metallic finish",
            "opulent yellow gold material",
        ],
        "lighting_tips": "Use warm-toned key light with soft fill to maintain the golden hue. Avoid cool blue lighting which makes gold look greenish. A dark background increases the richness of reflections.",
    },
    {
        "key": "silver",
        "material": "Polished Silver",
        "category": "metal",
        "description": "Cool, bright silver with mirror-like reflections and precise highlights that convey precision and modern elegance.",
        "prompt_keywords": [
            "polished silver metal surface",
            "cool bright silver reflections",
            "mirror-like silver sheen",
            "precise silver specular highlights",
            "brilliant silver metallic finish",
            "platinum-like silver luster",
        ],
        "lighting_tips": "Use cool white lighting for clean reflections. A large soft light source creates beautiful graduated reflections on curved surfaces. Keep environment clean as silver mirrors everything.",
    },
    {
        "key": "rose_gold",
        "material": "Rose Gold",
        "category": "metal",
        "description": "Warm pink-gold alloy with a modern, romantic luster that bridges the gap between gold's opulence and copper's warmth.",
        "prompt_keywords": [
            "rose gold metallic surface",
            "warm pink-gold luster",
            "modern rose gold finish",
            "romantic blush gold sheen",
            "pink-tinted gold reflections",
            "contemporary rose gold material",
        ],
        "lighting_tips": "Use warm to neutral lighting to preserve the pink undertone. Avoid overly warm light which shifts it to regular gold. Soft diffused lighting enhances the romantic quality.",
    },
    {
        "key": "brushed_steel",
        "material": "Brushed Steel",
        "category": "metal",
        "description": "Industrial stainless steel with fine directional brush marks that create a satin finish, diffusing reflections into soft streaks.",
        "prompt_keywords": [
            "brushed stainless steel surface",
            "fine directional brush marks",
            "satin steel finish",
            "industrial grade metal texture",
            "diffused linear reflections",
            "machined steel brushed pattern",
        ],
        "lighting_tips": "Light perpendicular to the brush direction to reveal the texture. Long strip lights create beautiful graduated reflections. The brush pattern softens harsh reflections naturally.",
    },
    {
        "key": "chrome",
        "material": "Mirror Chrome",
        "category": "metal",
        "description": "Perfect mirror-finish chrome with distortion-free reflections that capture the entire surrounding environment.",
        "prompt_keywords": [
            "mirror chrome surface",
            "perfect chrome reflections",
            "automotive quality chrome finish",
            "distortion-free polished chrome",
            "high-gloss chrome plating",
            "reflective chrome metal",
        ],
        "lighting_tips": "Control the environment carefully as chrome reflects everything. Use gradient backgrounds and large softboxes for clean reflections. A tent or light cone controls reflections on complex shapes.",
    },
    {
        "key": "copper",
        "material": "Copper",
        "category": "metal",
        "description": "Warm reddish-orange metal with a living surface that develops unique patina over time, conveying artisanal craftsmanship.",
        "prompt_keywords": [
            "copper metal surface",
            "warm reddish-orange copper tone",
            "developing copper patina",
            "artisanal hammered copper",
            "rich copper metallic warmth",
            "aged copper with verdigris hints",
        ],
        "lighting_tips": "Warm lighting enhances copper's natural tone. Side lighting reveals hammered texture. Mix warm and cool light to show both the copper tone and any green patina.",
    },
    {
        "key": "platinum",
        "material": "Platinum",
        "category": "metal",
        "description": "Dense, cool-white precious metal with a subtle understated luster that is brighter than silver but less flashy than chrome.",
        "prompt_keywords": [
            "platinum metal surface",
            "dense cool-white metal luster",
            "understated precious metal sheen",
            "bright white metal finish",
            "refined platinum reflections",
            "heavy luxurious platinum material",
        ],
        "lighting_tips": "Use neutral to slightly cool lighting. Platinum has more subtle reflections than silver so use slightly harder light to bring out its sheen. Dark surroundings add drama.",
    },
    {
        "key": "titanium",
        "material": "Titanium",
        "category": "metal",
        "description": "Lightweight aerospace-grade metal with a muted grey tone and subtle blue undertone that conveys high-tech precision.",
        "prompt_keywords": [
            "titanium metal surface",
            "muted grey aerospace metal",
            "subtle blue-grey titanium tone",
            "precision machined titanium",
            "high-tech lightweight metal finish",
            "industrial titanium material",
        ],
        "lighting_tips": "Neutral or slightly cool lighting enhances the blue-grey undertone. Hard lighting shows the machined precision. Works well with dark, minimal environments.",
    },
    {
        "key": "brass",
        "material": "Brass",
        "category": "metal",
        "description": "Warm yellow-gold alloy with vintage character, ranging from bright polish to aged dark patina with green oxidation.",
        "prompt_keywords": [
            "brass metal surface",
            "warm yellow-gold brass tone",
            "vintage brass patina",
            "antique brass finish",
            "heritage brass hardware quality",
            "aged brass warm oxidation",
        ],
        "lighting_tips": "Warm tungsten-like lighting enhances the vintage character. Side lighting reveals patina texture. Mixing old patinated and polished areas creates visual interest.",
    },
    {
        "key": "bronze",
        "material": "Bronze",
        "category": "metal",
        "description": "Dark warm alloy with rich brown tones and classical patina, evoking sculpture, heritage, and timeless craftsmanship.",
        "prompt_keywords": [
            "bronze metal surface",
            "rich dark brown bronze tone",
            "classical bronze patina",
            "sculptural bronze finish",
            "heritage cast bronze material",
            "antique bronze warm luster",
        ],
        "lighting_tips": "Warm directional lighting brings out the rich brown tones. Raking side light reveals sculptural texture and patina. Dark backgrounds emphasize the warmth.",
    },
    {
        "key": "matte_black_metal",
        "material": "Matte Black Metal",
        "category": "metal",
        "description": "Deep black metal finish with zero shine, absorbing nearly all light for a stealth, modern, and sophisticated appearance.",
        "prompt_keywords": [
            "matte black metal finish",
            "deep black anodized surface",
            "zero-shine dark metal",
            "stealth black metal coating",
            "light-absorbing black finish",
            "modern matte black material",
        ],
        "lighting_tips": "Use edge lighting and rim lights to define the shape since the surface absorbs frontal light. Slight specular highlights reveal the metallic nature. Contrast against lighter backgrounds.",
    },
    # =====================================================================
    # FABRIC
    # =====================================================================
    {
        "key": "silk",
        "material": "Silk",
        "category": "fabric",
        "description": "Smooth, lustrous natural fiber with a flowing drape and elegant light-catching surface that shimmers with movement.",
        "prompt_keywords": [
            "silk fabric lustrous surface",
            "smooth flowing silk drape",
            "light-catching silk sheen",
            "luxurious silk material",
            "shimmering silk folds",
            "elegant natural silk fiber",
        ],
        "lighting_tips": "Large soft light source creates beautiful graduated highlights across folds. Side lighting emphasizes the drape and reveals the luminous quality. Avoid harsh shadows.",
    },
    {
        "key": "satin",
        "material": "Satin",
        "category": "fabric",
        "description": "High-gloss weave with a mirror-like reflective surface and fluid drape that creates dramatic light and shadow contrasts.",
        "prompt_keywords": [
            "satin fabric high gloss surface",
            "mirror-like satin reflections",
            "fluid satin drape",
            "glossy smooth satin finish",
            "dramatic satin light and shadow",
            "luxurious satin sheen",
        ],
        "lighting_tips": "Side lighting creates dramatic specular highlights on the peaks of folds. Control highlights carefully as satin is very reflective. Dark tones need more controlled lighting to avoid blown highlights.",
    },
    {
        "key": "velvet",
        "material": "Velvet",
        "category": "fabric",
        "description": "Deep pile fabric that absorbs light in one direction and catches it in another, creating rich depth and a tactile visual softness.",
        "prompt_keywords": [
            "velvet fabric deep pile",
            "light-absorbing rich velvet",
            "tactile soft velvet texture",
            "luxurious velvet depth",
            "crushed velvet surface detail",
            "sumptuous velvet material",
        ],
        "lighting_tips": "Side lighting at a low angle reveals the pile direction and creates the characteristic two-tone effect. Frontal light kills the texture. Dark colors need careful exposure to retain detail.",
    },
    {
        "key": "cashmere",
        "material": "Cashmere",
        "category": "fabric",
        "description": "Ultra-soft premium wool fiber with a gentle fuzz and warmth that conveys understated luxury and comfort.",
        "prompt_keywords": [
            "cashmere wool ultra-soft texture",
            "gentle cashmere fiber fuzz",
            "premium knit cashmere quality",
            "warm luxurious cashmere material",
            "fine cashmere fiber detail",
            "soft cashmere sweater texture",
        ],
        "lighting_tips": "Soft backlight creates a halo effect on the fuzzy fibers. Gentle side lighting reveals the knit texture. Warm tones enhance the cozy feel.",
    },
    {
        "key": "cotton",
        "material": "Cotton",
        "category": "fabric",
        "description": "Natural breathable fiber with a matte, clean texture ranging from crisp poplin to soft jersey depending on weave.",
        "prompt_keywords": [
            "cotton fabric natural texture",
            "clean matte cotton surface",
            "breathable cotton weave visible",
            "crisp cotton material",
            "natural organic cotton fiber",
            "soft cotton fabric detail",
        ],
        "lighting_tips": "Natural daylight-style lighting works best for cotton's honest texture. Slight side light reveals the weave. Avoid overly dramatic lighting which feels wrong for this casual material.",
    },
    {
        "key": "linen",
        "material": "Linen",
        "category": "fabric",
        "description": "Natural flax fiber with visible slubs, relaxed creases, and an organic breathable quality that evokes Mediterranean ease.",
        "prompt_keywords": [
            "linen fabric natural fibers visible",
            "relaxed linen creases and wrinkles",
            "organic breathable linen texture",
            "natural slubby linen weave",
            "Mediterranean linen material",
            "rustic natural linen surface",
        ],
        "lighting_tips": "Warm natural light enhances linen's organic character. Side lighting reveals the slubs and natural texture. The wrinkles are a feature so embrace them with directional light.",
    },
    {
        "key": "leather_smooth",
        "material": "Smooth Leather",
        "category": "fabric",
        "description": "Premium full-grain leather with a supple, polished surface and subtle natural grain that conveys refined luxury.",
        "prompt_keywords": [
            "smooth premium leather surface",
            "full-grain polished leather",
            "supple conditioned leather texture",
            "luxury leather natural grain",
            "refined smooth leather material",
            "high-quality leather finish",
        ],
        "lighting_tips": "Large soft light creates graduated reflections that show the supple quality. Slight specularity reveals the polish. Warm lighting enhances brown tones.",
    },
    {
        "key": "leather_textured",
        "material": "Textured Leather",
        "category": "fabric",
        "description": "Heavily grained or embossed leather with pronounced texture patterns like crocodile, pebble, or basket weave.",
        "prompt_keywords": [
            "textured embossed leather surface",
            "pronounced leather grain pattern",
            "crocodile or pebble leather texture",
            "deeply grained leather material",
            "exotic textured leather finish",
            "tactile heavy-grain leather",
        ],
        "lighting_tips": "Raking side light at a low angle maximizes texture visibility. Harder light emphasizes the embossed pattern. Fill carefully to avoid losing detail in the crevices.",
    },
    {
        "key": "suede",
        "material": "Suede",
        "category": "fabric",
        "description": "Soft napped leather surface with a velvety matte finish that changes appearance based on the direction of the nap.",
        "prompt_keywords": [
            "suede napped leather surface",
            "velvety soft suede texture",
            "matte suede finish",
            "brushed suede material",
            "directional suede nap visible",
            "tactile suede leather quality",
        ],
        "lighting_tips": "Side lighting reveals the nap direction and creates the characteristic two-tone effect. Backlight creates a soft edge glow on the fuzzy surface. Avoid flat frontal light.",
    },
    {
        "key": "lace",
        "material": "Lace",
        "category": "fabric",
        "description": "Delicate openwork fabric with intricate patterns, combining solid threads with transparent gaps for a romantic, detailed aesthetic.",
        "prompt_keywords": [
            "delicate lace fabric intricate pattern",
            "openwork lace transparency",
            "handcrafted lace detail",
            "romantic lace overlay texture",
            "fine lace mesh and pattern",
            "bridal quality lace material",
        ],
        "lighting_tips": "Backlight to reveal the openwork pattern and transparency. Place over a contrasting color to show the pattern detail. Soft light prevents harsh shadows that obscure the delicacy.",
    },
    {
        "key": "tulle",
        "material": "Tulle",
        "category": "fabric",
        "description": "Sheer fine mesh fabric with ethereal layered transparency, commonly used in bridal and ballet for its cloud-like quality.",
        "prompt_keywords": [
            "tulle sheer mesh fabric",
            "ethereal layered tulle",
            "wedding quality tulle material",
            "cloud-like tulle transparency",
            "multiple tulle layers soft depth",
            "delicate tulle netting",
        ],
        "lighting_tips": "Backlight creates a beautiful glow through the layers. Multiple layers increase opacity creating depth gradients. Soft diffused light enhances the ethereal quality.",
    },
    {
        "key": "denim",
        "material": "Denim",
        "category": "fabric",
        "description": "Sturdy cotton twill weave dyed with indigo, featuring visible diagonal ribbing and authentic fade patterns from wear.",
        "prompt_keywords": [
            "denim fabric indigo blue",
            "cotton twill weave pattern visible",
            "authentic worn denim texture",
            "selvedge denim quality",
            "faded distressed denim material",
            "raw denim diagonal ribbing",
        ],
        "lighting_tips": "Natural daylight shows authentic indigo color. Side lighting reveals the twill weave texture. Highlight fade patterns and whisker marks with directional light.",
    },
    {
        "key": "tweed",
        "material": "Tweed",
        "category": "fabric",
        "description": "Woven multicolor wool fabric with a rough texture and heritage quality, associated with British tailoring and luxury fashion houses.",
        "prompt_keywords": [
            "tweed woven multicolor pattern",
            "heritage quality wool tweed",
            "rough textured tweed surface",
            "British tailoring tweed fabric",
            "Donegal flecked tweed material",
            "classic woven tweed texture",
        ],
        "lighting_tips": "Even soft lighting shows the multicolor flecks. Close-up with side light reveals the woven texture. Warm lighting enhances the heritage feel.",
    },
    {
        "key": "fur",
        "material": "Fur",
        "category": "fabric",
        "description": "Dense plush fiber with visible individual strands creating depth, softness, and a luxurious tactile appearance.",
        "prompt_keywords": [
            "plush dense fur texture",
            "individual fur strands visible",
            "luxurious soft fur material",
            "deep pile fur surface",
            "rich tactile fur depth",
            "fur fiber detail and softness",
        ],
        "lighting_tips": "Backlight creates a stunning rim-light halo on individual strands. Side light reveals depth in the pile. Avoid flat frontal light which flattens the three-dimensional texture.",
    },
    {
        "key": "chiffon",
        "material": "Chiffon",
        "category": "fabric",
        "description": "Ultra-sheer lightweight fabric that billows and floats with air movement, creating an ethereal and romantic quality.",
        "prompt_keywords": [
            "chiffon ultra-sheer fabric",
            "lightweight billowing chiffon",
            "floating transparent chiffon material",
            "ethereal chiffon movement",
            "gossamer thin chiffon drape",
            "wind-caught chiffon flow",
        ],
        "lighting_tips": "Backlight to show transparency and create a glowing effect. Use wind or movement to create dynamic flowing shapes. Soft ambient light enhances the dreamy quality.",
    },
    {
        "key": "organza",
        "material": "Organza",
        "category": "fabric",
        "description": "Crisp sheer fabric with more body and structure than chiffon, holding sculptural shapes while remaining transparent.",
        "prompt_keywords": [
            "organza crisp sheer fabric",
            "structured transparent organza",
            "sculptural organza material",
            "stiff sheer organza texture",
            "organza holding defined shape",
            "translucent rigid organza",
        ],
        "lighting_tips": "Side and back lighting show the structured transparency. The crisp nature creates defined folds with sharp edges that catch light differently than soft fabrics.",
    },
    {
        "key": "sequins",
        "material": "Sequins",
        "category": "fabric",
        "description": "Small reflective discs stitched to fabric creating a dazzling mosaic of individual light reflections and sparkle.",
        "prompt_keywords": [
            "sequin-covered fabric surface",
            "individual sequin light reflections",
            "sparkling sequin mosaic",
            "dazzling sequin texture detail",
            "glittering sequin material",
            "disco-ball sequin surface",
        ],
        "lighting_tips": "Use a single hard point light to create maximum sparkle. Moving the light or subject angle dramatically changes the reflection pattern. Multiple lights reduce the sparkle effect.",
    },
    # =====================================================================
    # SKIN
    # =====================================================================
    {
        "key": "skin_luminous",
        "material": "Luminous Skin",
        "category": "skin",
        "description": "Radiant glowing skin with visible inner luminosity, subtle highlights on high points, and a healthy lit-from-within quality.",
        "prompt_keywords": [
            "luminous radiant skin",
            "glowing inner luminosity",
            "lit-from-within skin quality",
            "healthy radiant complexion",
            "subtle highlight on cheekbones",
            "dewy luminous skin texture",
        ],
        "lighting_tips": "Large frontal soft light with slight top bias. Add subtle fill from below to create the inner glow. A reflector under the chin lifts shadows and adds luminosity.",
    },
    {
        "key": "skin_matte",
        "material": "Matte Skin",
        "category": "skin",
        "description": "Smooth even-toned skin with a shine-free matte finish, conveying a polished and professionally retouched beauty look.",
        "prompt_keywords": [
            "matte skin finish",
            "smooth even-toned complexion",
            "shine-free skin surface",
            "professional beauty skin texture",
            "poreless smooth matte skin",
            "refined matte complexion",
        ],
        "lighting_tips": "Soft beauty dish or large softbox directly in front and slightly above. Avoid hard specular highlights. Even, wrap-around lighting minimizes skin texture.",
    },
    {
        "key": "skin_dewy",
        "material": "Dewy Skin",
        "category": "skin",
        "description": "Fresh hydrated skin with visible moisture on the surface, creating glass-skin reflections and a youthful, just-misted appearance.",
        "prompt_keywords": [
            "dewy hydrated skin surface",
            "glass-skin moisture effect",
            "fresh misted skin texture",
            "visible hydration on skin",
            "wet-look dewy complexion",
            "youthful dewy skin glow",
        ],
        "lighting_tips": "Side lighting catches the moisture droplets and creates specular highlights. A ring light creates even dewy highlights. Mist with actual water for realistic dew effect.",
    },
    {
        "key": "skin_tanned",
        "material": "Tanned Skin",
        "category": "skin",
        "description": "Warm sun-kissed skin with golden bronze undertones, even tan lines, and a healthy outdoor glow.",
        "prompt_keywords": [
            "tanned sun-kissed skin",
            "golden bronze skin tone",
            "warm tanned complexion",
            "sun-bronzed skin glow",
            "healthy tanned skin surface",
            "golden warm skin undertone",
        ],
        "lighting_tips": "Warm golden-hour lighting enhances the tan. Side lighting shows the warm undertones. Avoid cool lighting which fights the naturally warm skin tone.",
    },
    {
        "key": "skin_fair",
        "material": "Fair Skin",
        "category": "skin",
        "description": "Pale porcelain-like complexion with cool pink undertones, visible translucency, and delicate fine texture.",
        "prompt_keywords": [
            "fair porcelain complexion",
            "pale skin cool pink undertones",
            "translucent fair skin quality",
            "delicate light complexion",
            "fine-textured fair skin surface",
            "luminous pale skin tone",
        ],
        "lighting_tips": "Soft cool-to-neutral lighting preserves the porcelain quality. Be careful with exposure as fair skin easily blows out. Subtle pink gels enhance the natural undertone.",
    },
    {
        "key": "skin_dark",
        "material": "Dark Skin",
        "category": "skin",
        "description": "Rich deep-toned complexion with beautiful specular highlights that reveal underlying warm or cool undertones and luminous depth.",
        "prompt_keywords": [
            "rich deep-toned dark skin",
            "luminous dark complexion",
            "beautiful specular highlights on dark skin",
            "warm undertones in dark skin",
            "radiant dark skin surface",
            "deep skin tone with natural glow",
        ],
        "lighting_tips": "Use plenty of light with large soft sources. Specular highlights are key to showing dimension. Avoid underexposure. Warm fill light reveals beautiful undertones.",
    },
    {
        "key": "skin_aged",
        "material": "Aged Skin",
        "category": "skin",
        "description": "Mature skin with visible lines, wrinkles, and character marks that tell a story of life experience and wisdom.",
        "prompt_keywords": [
            "aged mature skin texture",
            "visible wrinkles and fine lines",
            "character lines in skin",
            "weathered experienced skin surface",
            "textured aged complexion",
            "wisdom lines and skin character",
        ],
        "lighting_tips": "Side lighting reveals texture and character. Avoid flat frontal light which erases the lines. Hard directional light emphasizes every line for dramatic portraits.",
    },
    {
        "key": "skin_young",
        "material": "Young Skin",
        "category": "skin",
        "description": "Smooth youthful complexion with natural elasticity, even tone, subtle peach fuzz, and a fresh healthy appearance.",
        "prompt_keywords": [
            "smooth youthful skin texture",
            "fresh young complexion",
            "natural elastic skin quality",
            "even-toned youthful surface",
            "healthy young skin glow",
            "soft youthful skin appearance",
        ],
        "lighting_tips": "Soft frontal light enhances the smooth quality. Backlight can reveal fine peach fuzz beautifully. Large light sources wrap around the face for an even, youthful look.",
    },
    # =====================================================================
    # LIQUID
    # =====================================================================
    {
        "key": "water_drops",
        "material": "Water Drops",
        "category": "liquid",
        "description": "Individual water droplets beading on a surface, each acting as a tiny lens refracting the background and catching specular highlights.",
        "prompt_keywords": [
            "water droplets beading on surface",
            "individual drops as tiny lenses",
            "water bead refraction detail",
            "condensation droplets close-up",
            "water drops catching light",
            "dew drops on surface",
        ],
        "lighting_tips": "Backlight makes each drop glow as a tiny bright sphere. Macro lighting reveals internal refraction. Dark background makes drops stand out as bright spots.",
    },
    {
        "key": "pouring_water",
        "material": "Pouring Water",
        "category": "liquid",
        "description": "Continuous stream of clear water in motion, showing fluid dynamics with smooth laminar flow transitioning to turbulent splashing.",
        "prompt_keywords": [
            "pouring water stream",
            "clear water flowing in motion",
            "laminar to turbulent water flow",
            "dynamic water pour",
            "liquid stream clear water",
            "water in mid-pour motion",
        ],
        "lighting_tips": "Fast strobe freezes motion. Backlight reveals transparency and internal refraction. Side light creates specular streaks along the water column.",
    },
    {
        "key": "water_splash",
        "material": "Water Splash",
        "category": "liquid",
        "description": "Explosive high-speed water impact with frozen droplets suspended in air, creating dramatic dynamic shapes.",
        "prompt_keywords": [
            "dynamic water splash frozen motion",
            "high-speed water impact",
            "suspended water droplets in air",
            "explosive splash liquid dynamics",
            "frozen water crown splash",
            "dramatic water burst",
        ],
        "lighting_tips": "High-speed flash freezes the motion. Multiple rim lights create specular highlights on each droplet. Dark background makes the splash stand out dramatically.",
    },
    {
        "key": "condensation",
        "material": "Condensation",
        "category": "liquid",
        "description": "Fine mist of tiny water droplets forming on a cold surface, creating a foggy frosted effect with trails where drops have run.",
        "prompt_keywords": [
            "condensation mist on cold surface",
            "foggy frost water film",
            "cold glass condensation droplets",
            "moisture beading on chilled surface",
            "condensation trails and rivulets",
            "dewy cold surface moisture",
        ],
        "lighting_tips": "Backlight reveals the fog layer and individual droplets. Side lighting shows the trails where drops have run. Use actual cold temperature difference for realism.",
    },
    {
        "key": "oil_liquid",
        "material": "Oil",
        "category": "liquid",
        "description": "Viscous golden-amber liquid with slow flowing movement, warm translucency, and thick glossy surface tension.",
        "prompt_keywords": [
            "golden viscous oil liquid",
            "warm amber oil translucency",
            "thick glossy oil surface",
            "slow-flowing viscous oil",
            "rich golden oil drip",
            "cosmetic or culinary oil quality",
        ],
        "lighting_tips": "Backlight creates a warm amber glow through the oil. Side light shows surface glossiness. Warm lighting enhances the golden color naturally.",
    },
    {
        "key": "honey",
        "material": "Honey",
        "category": "liquid",
        "description": "Thick golden-amber honey with extremely slow viscous flow, visible string formations, and warm natural translucency.",
        "prompt_keywords": [
            "honey golden amber liquid",
            "viscous slow honey drip",
            "thick honey string formation",
            "warm translucent honey flow",
            "natural golden honey pour",
            "syrupy thick honey texture",
        ],
        "lighting_tips": "Strong backlight makes honey glow brilliantly golden. Capture the slow drip with continuous lighting. Warm tones amplify the natural amber color.",
    },
    {
        "key": "wine",
        "material": "Red Wine",
        "category": "liquid",
        "description": "Deep burgundy wine with visible legs on glass, rich color gradation from edge to center, and jewel-like translucency.",
        "prompt_keywords": [
            "red wine deep burgundy liquid",
            "wine legs visible on glass",
            "rich burgundy translucent color",
            "jewel-toned red wine",
            "sommelier quality wine in glass",
            "deep ruby wine surface",
        ],
        "lighting_tips": "Backlight through the glass reveals the rich color. Slight side light shows the legs. White surface below shows the wine's true color through refraction.",
    },
    {
        "key": "champagne_bubbles",
        "material": "Champagne Bubbles",
        "category": "liquid",
        "description": "Golden effervescent liquid with rising columns of tiny bubbles, creating a festive, celebratory, and luxurious atmosphere.",
        "prompt_keywords": [
            "champagne golden effervescent bubbles",
            "rising bubble columns in glass",
            "tiny champagne bubbles ascending",
            "sparkling celebration liquid",
            "golden fizzy champagne surface",
            "effervescent luxury champagne",
        ],
        "lighting_tips": "Backlight to make each bubble glow individually. Macro lens reveals bubble detail. Dark background with single key light creates the most dramatic champagne imagery.",
    },
    {
        "key": "milk",
        "material": "Milk",
        "category": "liquid",
        "description": "Pure white opaque liquid with a smooth creamy surface, subtle shadows in the depth, and clean wholesome appearance.",
        "prompt_keywords": [
            "pure white milk liquid",
            "creamy opaque milk surface",
            "smooth white milk pour",
            "clean wholesome milk texture",
            "fresh milk splash white",
            "dense creamy milk material",
        ],
        "lighting_tips": "Soft frontal light shows the clean white quality. Avoid colored lights that tint the milk. High-speed flash freezes splashes beautifully. Slight shadow adds depth.",
    },
    {
        "key": "juice",
        "material": "Fresh Juice",
        "category": "liquid",
        "description": "Vibrant naturally colored fruit juice with visible pulp texture, fresh appearance, and translucent fruit-toned color.",
        "prompt_keywords": [
            "fresh fruit juice vibrant color",
            "visible pulp texture in juice",
            "translucent natural juice tone",
            "freshly squeezed juice appearance",
            "bright colorful fruit juice",
            "natural juice with fruit bits",
        ],
        "lighting_tips": "Backlight reveals the natural color and any pulp particles. Match lighting color temperature to the juice tone for accuracy. Fresh garnish adds authenticity.",
    },
    # =====================================================================
    # FOOD
    # =====================================================================
    {
        "key": "steam_rising",
        "material": "Steam Rising",
        "category": "food",
        "description": "Visible wisps of hot steam curling upward from food or drink, conveying freshness, warmth, and appetite appeal.",
        "prompt_keywords": [
            "steam rising from hot food",
            "visible wisps of hot vapor",
            "curling steam tendrils",
            "warm steam conveying freshness",
            "appetizing steam above dish",
            "hot food vapor visible",
        ],
        "lighting_tips": "Backlight is essential to make steam visible. Dark background behind the steam maximizes visibility. Avoid frontal light which makes steam disappear.",
    },
    {
        "key": "melting_cheese",
        "material": "Melting Cheese",
        "category": "food",
        "description": "Gooey stretching melted cheese with visible stringy pull, golden brown bubbled surface, and appetizing glossy texture.",
        "prompt_keywords": [
            "melting cheese stringy pull",
            "gooey stretching cheese texture",
            "golden brown bubbled cheese",
            "appetizing melted cheese surface",
            "glossy melting cheese drip",
            "hot melting cheese stretch",
        ],
        "lighting_tips": "Warm side lighting creates appetizing golden tones. Capture the cheese pull at peak stretch. Slight backlighting shows translucency in thin stretched areas.",
    },
    {
        "key": "crispy_texture",
        "material": "Crispy Texture",
        "category": "food",
        "description": "Crunchy golden-brown fried or baked surface with visible crackle, flaky layers, and an audibly crisp appearance.",
        "prompt_keywords": [
            "crispy golden-brown surface",
            "crunchy fried texture visible",
            "flaky crackled crisp coating",
            "perfectly crisped food surface",
            "audibly crunchy texture detail",
            "golden crisp food finish",
        ],
        "lighting_tips": "Hard side light at a low angle reveals every crispy ridge and flake. Warm lighting enhances the golden-brown color. Close-up reveals the satisfying crunch texture.",
    },
    {
        "key": "fresh_produce",
        "material": "Fresh Produce",
        "category": "food",
        "description": "Just-picked fruits and vegetables with vibrant natural colors, taut skin, water mist droplets, and peak freshness appearance.",
        "prompt_keywords": [
            "fresh produce vibrant natural color",
            "just-picked fruit and vegetable",
            "water mist droplets on produce",
            "taut skin fresh produce surface",
            "peak freshness food quality",
            "garden-fresh produce detail",
        ],
        "lighting_tips": "Natural daylight-style lighting shows true colors. Water misting adds freshness cues. Soft fill prevents dark shadows that make produce look old.",
    },
    {
        "key": "chocolate_dripping",
        "material": "Dripping Chocolate",
        "category": "food",
        "description": "Rich glossy melted chocolate flowing and dripping with a smooth liquid surface, deep brown color, and decadent viscosity.",
        "prompt_keywords": [
            "rich glossy melted chocolate",
            "smooth chocolate drip flowing",
            "deep brown chocolate surface",
            "decadent liquid chocolate pour",
            "shiny chocolate ganache texture",
            "viscous melting chocolate",
        ],
        "lighting_tips": "Specular highlights show the glossy surface. Warm side lighting enhances the rich brown color. Dark background makes chocolate the star. Slight backlight adds depth.",
    },
    {
        "key": "ice_cream_melting",
        "material": "Melting Ice Cream",
        "category": "food",
        "description": "Scooped ice cream beginning to melt with drips running down the side, soft creamy texture transitioning to liquid at the edges.",
        "prompt_keywords": [
            "melting ice cream drips running",
            "soft creamy ice cream texture",
            "scooped ice cream melting edges",
            "ice cream transitioning to liquid",
            "creamy melting ice cream surface",
            "dripping melting ice cream detail",
        ],
        "lighting_tips": "Work fast as ice cream melts under hot lights. Use continuous cool lighting or flash. Side light shows the texture transition from frozen to melted.",
    },
    {
        "key": "bread_crust",
        "material": "Bread Crust",
        "category": "food",
        "description": "Artisan bread with a crackled golden-brown crust, visible scoring marks, and the promise of a soft interior.",
        "prompt_keywords": [
            "artisan bread golden-brown crust",
            "crackled bread surface scoring",
            "freshly baked bread crust",
            "rustic bread crust texture",
            "crusty bread surface detail",
            "bakery quality bread finish",
        ],
        "lighting_tips": "Warm side lighting at a low angle reveals every crack and crevice in the crust. Slight steam adds freshness. Dark, rustic background enhances the artisan feel.",
    },
    {
        "key": "sushi",
        "material": "Sushi",
        "category": "food",
        "description": "Precision-crafted sushi with glistening fresh fish, perfectly formed rice, and meticulous presentation conveying Japanese culinary art.",
        "prompt_keywords": [
            "fresh glistening sushi fish",
            "precision-crafted sushi presentation",
            "glossy raw fish surface",
            "perfect sushi rice grains visible",
            "Japanese culinary art detail",
            "meticulous sushi plating",
        ],
        "lighting_tips": "Soft overhead lighting shows the glisten on raw fish. Avoid harsh shadows that darken the fish. Natural cool-to-neutral lighting preserves true color of each fish type.",
    },
    # =====================================================================
    # HAIR
    # =====================================================================
    {
        "key": "hair_straight_silky",
        "material": "Straight Silky Hair",
        "category": "hair",
        "description": "Perfectly smooth straight hair with a mirror-like shine, light-catching reflections, and a sleek glossy appearance.",
        "prompt_keywords": [
            "straight silky smooth hair",
            "mirror-like hair shine",
            "sleek glossy hair surface",
            "light-catching hair reflections",
            "perfectly smooth hair strands",
            "salon-quality straight hair",
        ],
        "lighting_tips": "Large overhead soft light creates a broad specular band of shine. Backlight creates a beautiful rim light on the hair outline. Side light shows individual strand detail.",
    },
    {
        "key": "hair_wavy",
        "material": "Wavy Hair",
        "category": "hair",
        "description": "Natural flowing waves with alternating light and shadow in each curve, creating rhythm, movement, and effortless volume.",
        "prompt_keywords": [
            "natural flowing wavy hair",
            "soft waves with movement",
            "light and shadow in hair curves",
            "effortless wavy hair volume",
            "beachy natural waves",
            "rhythmic wavy hair texture",
        ],
        "lighting_tips": "Side lighting emphasizes the wave pattern through light-shadow alternation. Backlight creates a glowing halo. Allow natural movement for dynamic wave shapes.",
    },
    {
        "key": "hair_curly",
        "material": "Curly Hair",
        "category": "hair",
        "description": "Defined spiral curls with spring-like bounce, volume, and individual coil definition creating a rich textural landscape.",
        "prompt_keywords": [
            "defined spiral curly hair",
            "bouncy coiled hair curls",
            "voluminous curly hair texture",
            "individual curl definition visible",
            "rich curly hair landscape",
            "natural coiled hair pattern",
        ],
        "lighting_tips": "Backlight creates stunning rim light on each curl. Side light adds depth and dimension to the curls. Large soft sources prevent harsh shadows in the curl valleys.",
    },
    {
        "key": "hair_braided",
        "material": "Braided Hair",
        "category": "hair",
        "description": "Intricately woven braided hairstyle with visible pattern structure, precision crossover detail, and geometric beauty.",
        "prompt_keywords": [
            "intricate braided hair pattern",
            "woven braid crossover detail",
            "precision braided hairstyle",
            "geometric braid structure",
            "detailed hair braiding texture",
            "elaborate braided hair design",
        ],
        "lighting_tips": "Side lighting reveals the woven texture and crossover pattern. Overhead light shows the geometric structure. Close-up reveals the precision craftsmanship.",
    },
    {
        "key": "hair_wet",
        "material": "Wet Hair",
        "category": "hair",
        "description": "Water-soaked hair clinging together in thick strands with intense specular shine and a dramatic slicked appearance.",
        "prompt_keywords": [
            "wet soaked hair slicked down",
            "water-drenched hair strands",
            "intense specular wet hair shine",
            "dramatic wet hair clinging",
            "glistening wet hair surface",
            "rain-soaked hair texture",
        ],
        "lighting_tips": "Hard specular light creates intense wet highlights. Backlight shows water droplets on strand edges. Dark background makes the wet shine more dramatic.",
    },
    {
        "key": "hair_windblown",
        "material": "Wind-Blown Hair",
        "category": "hair",
        "description": "Hair caught in motion by wind, creating dynamic flowing shapes, revealing movement and energy in a frozen moment.",
        "prompt_keywords": [
            "wind-blown hair in motion",
            "dynamic flowing hair movement",
            "hair caught by wind",
            "dramatic windswept hair",
            "frozen movement hair strands",
            "energetic wind-tossed hair",
        ],
        "lighting_tips": "Backlight separates flying strands from background. Fast shutter or flash freezes the motion. Side light adds dimension to the flowing shapes.",
    },
    {
        "key": "hair_grey_silver",
        "material": "Grey Silver Hair",
        "category": "hair",
        "description": "Naturally grey or silver-white hair with a distinguished luminous quality, varying tones from pewter to bright silver.",
        "prompt_keywords": [
            "grey silver distinguished hair",
            "luminous silver-white hair",
            "natural grey hair elegance",
            "pewter to bright silver tones",
            "dignified grey hair quality",
            "silver hair subtle shimmer",
        ],
        "lighting_tips": "Cool-toned light enhances the silver quality. Warm light can make grey hair look yellow so be careful. Backlight creates a beautiful silver halo effect.",
    },
    # =====================================================================
    # WOOD
    # =====================================================================
    {
        "key": "oak",
        "material": "Oak Wood",
        "category": "wood",
        "description": "Warm honey-toned hardwood with prominent cathedral grain patterns, conveying strength, tradition, and fine furniture craftsmanship.",
        "prompt_keywords": [
            "oak wood warm grain pattern",
            "cathedral oak grain detail",
            "honey-toned oak surface",
            "fine oak furniture quality",
            "prominent oak wood grain",
            "traditional oak hardwood",
        ],
        "lighting_tips": "Warm side lighting reveals grain depth and figure. Raking light at low angles maximizes grain visibility. Oil finishes create richer grain contrast under light.",
    },
    {
        "key": "walnut",
        "material": "Walnut Wood",
        "category": "wood",
        "description": "Rich dark brown hardwood with swirling grain patterns, ranging from deep chocolate to lighter sapwood with exceptional depth.",
        "prompt_keywords": [
            "dark walnut wood grain",
            "rich brown walnut surface",
            "swirling walnut grain pattern",
            "premium walnut furniture quality",
            "deep chocolate walnut tone",
            "polished walnut hardwood",
        ],
        "lighting_tips": "Warm lighting enhances the rich brown tones. Side lighting reveals the swirling grain. A polished finish reflects light beautifully and adds depth to the grain.",
    },
    {
        "key": "bamboo",
        "material": "Bamboo",
        "category": "wood",
        "description": "Light-colored sustainable grass material with distinctive nodes, fine parallel grain, and a clean modern aesthetic.",
        "prompt_keywords": [
            "bamboo natural light surface",
            "visible bamboo nodes and grain",
            "sustainable bamboo material",
            "fine parallel bamboo grain",
            "clean modern bamboo texture",
            "natural blonde bamboo finish",
        ],
        "lighting_tips": "Neutral to warm light shows the natural blonde color. Side lighting reveals the node patterns and fine grain. Clean even lighting suits bamboo's modern aesthetic.",
    },
    {
        "key": "driftwood",
        "material": "Driftwood",
        "category": "wood",
        "description": "Sun-bleached and water-worn wood with smooth organic shapes, grey-silver tone, and a natural sculptural quality.",
        "prompt_keywords": [
            "driftwood weathered bleached surface",
            "water-worn smooth wood grain",
            "grey-silver driftwood tone",
            "organic sculptural driftwood shape",
            "sun-bleached natural wood",
            "coastal driftwood texture",
        ],
        "lighting_tips": "Natural diffused light suits the organic character. Side lighting shows the smooth worn texture. Cool-toned light enhances the grey-silver coloring.",
    },
    {
        "key": "mahogany",
        "material": "Mahogany",
        "category": "wood",
        "description": "Deep reddish-brown tropical hardwood with fine straight grain and a natural luster that deepens with age and polish.",
        "prompt_keywords": [
            "mahogany deep reddish-brown wood",
            "fine straight mahogany grain",
            "polished mahogany luster",
            "luxurious mahogany furniture quality",
            "rich red-toned mahogany surface",
            "aged deep mahogany patina",
        ],
        "lighting_tips": "Warm lighting amplifies the red tones. Slight specularity shows the polished surface. Raking light reveals the fine straight grain pattern.",
    },
    {
        "key": "pine",
        "material": "Pine Wood",
        "category": "wood",
        "description": "Light softwood with prominent knots, visible resin marks, and a casual rustic character popular in farmhouse and Scandinavian design.",
        "prompt_keywords": [
            "pine wood light knotty surface",
            "visible pine knots and grain",
            "rustic pine wood texture",
            "light blonde pine material",
            "Scandinavian pine furniture quality",
            "natural knotty pine detail",
        ],
        "lighting_tips": "Warm natural light enhances the blonde tone. Side lighting shows knot detail and grain. Very warm light can make pine look orange so balance carefully.",
    },
    # =====================================================================
    # STONE
    # =====================================================================
    {
        "key": "marble_white",
        "material": "White Marble",
        "category": "stone",
        "description": "Luxurious white marble with dramatic grey or gold veining, polished to a mirror finish, evoking classical architecture and opulence.",
        "prompt_keywords": [
            "white marble polished surface",
            "dramatic marble grey veining",
            "Carrara marble luxury quality",
            "mirror-finished white marble",
            "classical marble stone texture",
            "elegant veined white marble",
        ],
        "lighting_tips": "Raking side light at a low angle reveals the veining depth. Slight backlighting shows translucency in thin sections. Cool light preserves the white purity.",
    },
    {
        "key": "marble_black",
        "material": "Black Marble",
        "category": "stone",
        "description": "Deep black marble with dramatic white or gold veining, polished to a glossy finish, creating a bold luxurious statement.",
        "prompt_keywords": [
            "black marble polished surface",
            "dramatic white veining on black",
            "Nero Marquina marble quality",
            "glossy deep black marble",
            "bold black marble statement",
            "dark marble gold vein detail",
        ],
        "lighting_tips": "Controlled lighting prevents losing detail in the dark areas. Side light reveals the veining dramatically. Specular reflections on the polished surface show the depth.",
    },
    {
        "key": "granite",
        "material": "Granite",
        "category": "stone",
        "description": "Hard igneous rock with a speckled crystalline appearance from interlocking mineral grains in various colors.",
        "prompt_keywords": [
            "granite speckled crystalline surface",
            "interlocking mineral grain pattern",
            "polished granite stone texture",
            "hard durable granite material",
            "multicolor granite crystal detail",
            "natural granite stone finish",
        ],
        "lighting_tips": "Close-up with side light reveals individual crystal grains. Polished granite has specular reflections that need control. Even lighting shows the full speckle pattern.",
    },
    {
        "key": "concrete",
        "material": "Concrete",
        "category": "stone",
        "description": "Raw poured concrete with industrial character, visible aggregate, subtle imperfections, and modern brutalist aesthetic.",
        "prompt_keywords": [
            "raw concrete industrial surface",
            "brutalist concrete texture",
            "visible concrete aggregate",
            "modern architectural concrete",
            "board-formed concrete pattern",
            "urban concrete material finish",
        ],
        "lighting_tips": "Directional side light reveals the raw texture and imperfections. Overcast lighting suits the industrial mood. Warm-toned light can soften the cold grey character.",
    },
    {
        "key": "terrazzo",
        "material": "Terrazzo",
        "category": "stone",
        "description": "Composite material with colorful stone chips embedded in polished cement, creating a confetti-like decorative surface.",
        "prompt_keywords": [
            "terrazzo polished stone chip surface",
            "colorful embedded aggregate terrazzo",
            "Italian luxury terrazzo flooring",
            "confetti-like terrazzo pattern",
            "polished cement with stone chips",
            "decorative terrazzo material",
        ],
        "lighting_tips": "Even overhead lighting shows the full pattern clearly. Polished terrazzo has specular reflections to control. Close-up reveals individual stone chip colors and shapes.",
    },
    {
        "key": "slate",
        "material": "Slate",
        "category": "stone",
        "description": "Layered metamorphic stone with a naturally flat cleavage plane, dark grey tones, and a sophisticated architectural quality.",
        "prompt_keywords": [
            "slate stone layered texture",
            "dark grey slate surface",
            "natural flat cleavage slate",
            "architectural slate material",
            "stratified slate stone detail",
            "natural slate grey tone",
        ],
        "lighting_tips": "Side lighting reveals the layered stratification. The flat surface catches light evenly. Water slightly darkens slate and adds surface interest.",
    },
    {
        "key": "sandstone",
        "material": "Sandstone",
        "category": "stone",
        "description": "Warm-toned sedimentary stone with visible granular texture and banded color layers ranging from cream to deep orange-red.",
        "prompt_keywords": [
            "sandstone warm granular texture",
            "banded color layers in sandstone",
            "natural sandstone warm tone",
            "sedimentary sandstone grain visible",
            "desert sandstone surface",
            "layered sandstone material",
        ],
        "lighting_tips": "Golden-hour warm light amplifies the natural warm tones beautifully. Side lighting reveals the granular texture and banded layers. Even light shows the full color range.",
    },
    {
        "key": "travertine",
        "material": "Travertine",
        "category": "stone",
        "description": "Warm cream-toned limestone with characteristic natural pitting and holes, conveying Roman luxury and timeless elegance.",
        "prompt_keywords": [
            "travertine warm cream stone",
            "natural pitting in travertine",
            "Roman luxury travertine material",
            "cream-toned travertine surface",
            "filled and polished travertine",
            "classical travertine stone texture",
        ],
        "lighting_tips": "Warm side lighting enhances the cream tones and reveals the natural pitting. Raking light creates shadows in the holes for maximum texture. Filled travertine looks smoother.",
    },
    # =====================================================================
    # PAPER
    # =====================================================================
    {
        "key": "paper_matte",
        "material": "Matte Paper",
        "category": "paper",
        "description": "Smooth uncoated paper with zero gloss, soft light absorption, and a clean professional appearance for printing and stationery.",
        "prompt_keywords": [
            "matte uncoated paper surface",
            "smooth zero-gloss paper",
            "soft light-absorbing paper finish",
            "professional matte stationery",
            "clean matte paper texture",
            "uncoated smooth paper material",
        ],
        "lighting_tips": "Even soft lighting works best as matte paper has no specular reflections. Side light can reveal subtle fiber texture. Avoid harsh light which creates unflattering shadows on edges.",
    },
    {
        "key": "paper_glossy",
        "material": "Glossy Paper",
        "category": "paper",
        "description": "High-shine coated paper with mirror-like reflections that make colors appear vivid and saturated, like a photo print.",
        "prompt_keywords": [
            "glossy coated paper surface",
            "high-shine reflective paper",
            "vivid color glossy finish",
            "photo-quality glossy paper",
            "mirror-like paper coating",
            "saturated color glossy material",
        ],
        "lighting_tips": "Control angle carefully to avoid direct specular reflections that create white hotspots. Diffused lighting shows colors best. Tilt the paper to manage reflection angle.",
    },
    {
        "key": "paper_textured_art",
        "material": "Textured Art Paper",
        "category": "paper",
        "description": "Heavyweight paper with visible tooth and fiber texture, deckled edges, and a handmade artisanal quality for fine art printing.",
        "prompt_keywords": [
            "textured art paper visible tooth",
            "heavyweight cotton rag paper",
            "handmade deckled edge paper",
            "artisanal fine art paper surface",
            "visible fiber texture art paper",
            "watercolor paper tactile quality",
        ],
        "lighting_tips": "Raking side light reveals the surface tooth and fiber texture. Backlight through the edge shows the deckle beautifully. Warm light enhances the natural cream tone.",
    },
    {
        "key": "kraft_paper",
        "material": "Kraft Paper",
        "category": "paper",
        "description": "Unbleached brown recycled paper with a rough natural texture, eco-friendly character, and rustic packaging aesthetic.",
        "prompt_keywords": [
            "kraft brown paper surface",
            "unbleached natural paper texture",
            "eco-friendly kraft material",
            "rustic brown paper finish",
            "recycled kraft paper grain",
            "natural brown wrapping paper",
        ],
        "lighting_tips": "Warm natural light enhances the earthy brown tone. Side lighting reveals the rough fiber texture. Works well with rustic styling and natural props.",
    },
    # =====================================================================
    # CERAMIC
    # =====================================================================
    {
        "key": "porcelain",
        "material": "Porcelain",
        "category": "ceramic",
        "description": "Fine white ceramic with a smooth translucent quality, delicate thin walls, and a refined elegant surface associated with fine dining.",
        "prompt_keywords": [
            "fine white porcelain surface",
            "smooth translucent porcelain",
            "delicate thin porcelain quality",
            "refined porcelain ceramic",
            "elegant porcelain finish",
            "bone china porcelain material",
        ],
        "lighting_tips": "Backlight reveals the translucency of thin porcelain. Soft diffused light shows the smooth surface. Slight warmth prevents porcelain from looking clinical.",
    },
    {
        "key": "matte_clay",
        "material": "Matte Clay",
        "category": "ceramic",
        "description": "Unglazed raw ceramic with a dry matte surface, visible hand-forming marks, and an honest artisanal earthiness.",
        "prompt_keywords": [
            "matte unglazed clay surface",
            "raw ceramic dry texture",
            "hand-formed clay marks visible",
            "artisanal matte pottery",
            "earthy unfinished clay material",
            "organic matte ceramic finish",
        ],
        "lighting_tips": "Side lighting reveals hand-forming marks and the matte texture. Even soft light shows the earthy color. Avoid specular highlights which contradict the matte character.",
    },
    {
        "key": "glazed_ceramic",
        "material": "Glazed Ceramic",
        "category": "ceramic",
        "description": "Kiln-fired ceramic with a smooth glass-like glaze coating that creates rich color depth and controlled specular reflections.",
        "prompt_keywords": [
            "glazed ceramic smooth coating",
            "glass-like ceramic glaze",
            "kiln-fired glossy ceramic",
            "rich color glazed surface",
            "specular glazed ceramic finish",
            "smooth fired ceramic material",
        ],
        "lighting_tips": "Control specular highlights on the glossy glaze. Soft overhead lighting creates clean gradual reflections on curved forms. Colored glazes need neutral light for true color.",
    },
    {
        "key": "terracotta",
        "material": "Terracotta",
        "category": "ceramic",
        "description": "Warm orange-brown fired clay with a rustic porous texture, Mediterranean character, and natural earthy warmth.",
        "prompt_keywords": [
            "terracotta warm orange-brown clay",
            "rustic porous terracotta surface",
            "Mediterranean terracotta material",
            "earthy fired terracotta texture",
            "natural terracotta pot quality",
            "warm rustic terracotta finish",
        ],
        "lighting_tips": "Warm golden light amplifies the natural orange-brown tone. Side lighting reveals the porous texture. Mediterranean-style natural light is the most authentic choice.",
    },
]

MATERIAL_BY_KEY = {material["key"]: material for material in TEXTURE_MATERIALS}
