"""
Scene Archetypes — 25+ advertising scene types with optimal settings.

Each archetype defines the ideal camera, lighting, duration, transition,
and prompt templates for that type of shot in professional advertising.
"""

from __future__ import annotations

SCENE_ARCHETYPES: dict[str, dict] = {
    "product_hero": {
        "description": "The signature product shot — the money shot of the ad",
        "optimal_duration": 4.0,
        "camera_movement": "orbit",
        "transition_in": "dissolve",
        "lighting": "Three-point with strong rim light, dark background for contrast",
        "lens": "100mm macro f/2.8",
        "composition": "center-frame, negative space, floating or on pedestal",
        "gemini_prompt_template": "{product} centered in frame, dramatic studio lighting with strong rim light, dark background, pristine surface, {brand_style}, commercial product photography, 8K detail, sharp focus throughout",
        "kling_prompt_template": "Slow 360-degree orbit around {product}, smooth camera movement, dramatic lighting shifts as camera moves, reflections catching light, {duration}s, cinematic",
        "keywords": ["product hero shot", "commercial photography", "dramatic lighting", "center composition"],
    },
    "lifestyle": {
        "description": "Product or mannequin in a real-world aspirational setting",
        "optimal_duration": 5.0,
        "camera_movement": "tracking",
        "transition_in": "fade",
        "lighting": "Natural light, golden hour or lifestyle setting ambient",
        "lens": "35mm f/1.4",
        "composition": "rule of thirds, environmental context, depth layers",
        "gemini_prompt_template": "{subject} in {environment}, natural lifestyle setting, authentic moment, {mood} atmosphere, environmental portrait, shallow depth of field, lifestyle photography, editorial quality",
        "kling_prompt_template": "Gentle camera tracking following {subject}, natural movement, ambient atmosphere, subtle environmental motion, {duration}s",
        "keywords": ["lifestyle photography", "environmental portrait", "authentic", "aspirational"],
    },
    "portrait": {
        "description": "Close-up or medium shot of the mannequin — beauty/fashion focus",
        "optimal_duration": 4.0,
        "camera_movement": "static",
        "transition_in": "dissolve",
        "lighting": "Beauty lighting — butterfly or clamshell, fill light",
        "lens": "85mm f/1.4",
        "composition": "center or slight off-center, headroom, eye-level",
        "gemini_prompt_template": "{mannequin_description} portrait, {clothing}, beauty lighting with butterfly setup, {mood} expression, shallow depth of field, fashion editorial, skin detail, 85mm lens bokeh",
        "kling_prompt_template": "Subtle mannequin movement, gentle head turn or gaze shift, hair movement, {duration}s, intimate portrait feel",
        "keywords": ["portrait photography", "beauty lighting", "fashion editorial", "intimate"],
    },
    "interaction": {
        "description": "Mannequin interacting with the product — touching, holding, using",
        "optimal_duration": 5.0,
        "camera_movement": "dolly_in",
        "transition_in": "fade",
        "lighting": "Mixed — beauty light on face, product light on item",
        "lens": "50mm f/1.2",
        "composition": "mid-shot, both mannequin and product visible, leading lines to product",
        "gemini_prompt_template": "{mannequin_description} {interaction} with {product}, {environment}, dual lighting on face and product, medium shot, commercial photography, both subject and product in sharp focus",
        "kling_prompt_template": "Mannequin smoothly {interaction_motion} with {product}, natural hand movement, camera slowly dollying in to product, {duration}s",
        "keywords": ["product interaction", "commercial", "dual subject", "hands detail"],
    },
    "establishing": {
        "description": "Wide shot setting the scene — location, mood, atmosphere",
        "optimal_duration": 4.0,
        "camera_movement": "crane_up",
        "transition_in": "fade",
        "lighting": "Environmental — depends on setting (golden hour, blue hour, night)",
        "lens": "24mm f/2.8",
        "composition": "wide angle, environmental depth, sky or ceiling visible",
        "gemini_prompt_template": "Wide establishing shot of {environment}, {time_of_day} lighting, atmospheric depth, cinematic wide angle, {mood} ambiance, film grain, landscape photography",
        "kling_prompt_template": "Slow crane up revealing {environment}, atmospheric elements moving (clouds, trees, water), cinematic sweep, {duration}s",
        "keywords": ["establishing shot", "wide angle", "cinematic", "environmental"],
    },
    "macro_detail": {
        "description": "Extreme close-up of product texture, material, or detail",
        "optimal_duration": 3.0,
        "camera_movement": "zoom_in",
        "transition_in": "cut",
        "lighting": "Focused spot or ring light, dark background",
        "lens": "100mm macro f/2.8",
        "composition": "full-frame detail, shallow DOF, abstract quality",
        "gemini_prompt_template": "Extreme macro close-up of {detail}, {material} texture visible, {lighting_quality}, razor-sharp focus on detail, abstract quality, commercial macro photography, 8K resolution",
        "kling_prompt_template": "Slow zoom into {detail}, revealing texture and craftsmanship, light playing across surface, {duration}s",
        "keywords": ["macro photography", "texture detail", "extreme close-up", "material rendering"],
    },
    "endframe": {
        "description": "Final brand shot — logo, product, tagline, call to action",
        "optimal_duration": 3.0,
        "camera_movement": "static",
        "transition_in": "dissolve",
        "lighting": "Clean, even — brand colors prominent",
        "lens": "50mm f/2.8",
        "composition": "centered, clean background, logo placement area",
        "gemini_prompt_template": "{product} final hero shot, clean {brand_color} background, brand-aligned lighting, centered composition, space for logo overlay, premium commercial photography",
        "kling_prompt_template": "Subtle light shift on {product}, gentle sparkle or reflection, elegant stillness, {duration}s, luxury endframe",
        "keywords": ["endframe", "brand shot", "logo placement", "clean composition"],
    },
    "packshot": {
        "description": "Clean product packaging shot — e-commerce or catalog style",
        "optimal_duration": 3.0,
        "camera_movement": "static",
        "transition_in": "cut",
        "lighting": "Even softbox lighting, no harsh shadows",
        "lens": "90mm f/5.6",
        "composition": "dead center, white or gradient background, full product visible",
        "gemini_prompt_template": "{product} packshot, clean studio photography, even softbox lighting, {background} background, full product visible, sharp throughout, commercial catalog quality",
        "kling_prompt_template": "Static packshot with subtle light animation, gentle reflection shift, {duration}s, clean commercial",
        "keywords": ["packshot", "catalog", "clean studio", "even lighting"],
    },
    "unboxing": {
        "description": "Product being revealed from packaging",
        "optimal_duration": 5.0,
        "camera_movement": "dolly_in",
        "transition_in": "dissolve",
        "lighting": "Warm overhead, slight dramatic shadow",
        "lens": "50mm f/1.8",
        "composition": "top-down or slight angle, hands visible, sequential reveal",
        "gemini_prompt_template": "{product} emerging from premium packaging, {angle} view, hands carefully revealing product, warm overhead lighting, luxury unboxing moment, anticipation, sharp focus on product",
        "kling_prompt_template": "Smooth unboxing motion, hands lifting {product} from packaging, camera dollying in as product is revealed, {duration}s",
        "keywords": ["unboxing", "reveal", "premium packaging", "anticipation"],
    },
    "before_after": {
        "description": "Transformation or comparison shot",
        "optimal_duration": 5.0,
        "camera_movement": "pan_left",
        "transition_in": "wipe",
        "lighting": "Consistent between both states",
        "lens": "50mm f/2.8",
        "composition": "split frame or sequential, matching angles",
        "gemini_prompt_template": "{before_state} transitioning to {after_state}, split composition, consistent lighting between states, {product} as catalyst, commercial transformation photography",
        "kling_prompt_template": "Smooth pan or wipe transition from before to after state, {product} visible, transformation evident, {duration}s",
        "keywords": ["before after", "transformation", "comparison", "split frame"],
    },
    "testimonial": {
        "description": "Person speaking to camera or showing satisfaction",
        "optimal_duration": 5.0,
        "camera_movement": "static",
        "transition_in": "fade",
        "lighting": "Soft, flattering — beauty dish or large softbox",
        "lens": "85mm f/2.0",
        "composition": "medium close-up, slight off-center, eye contact",
        "gemini_prompt_template": "{mannequin_description} in testimonial pose, warm genuine expression, soft flattering lighting, blurred background, medium close-up, authentic moment, editorial portrait",
        "kling_prompt_template": "Mannequin speaking naturally, subtle gestures, genuine expression, slight head movement, {duration}s, authentic feel",
        "keywords": ["testimonial", "authentic", "speaking", "genuine expression"],
    },
    "action": {
        "description": "Dynamic movement — running, jumping, sports, dance",
        "optimal_duration": 4.0,
        "camera_movement": "tracking",
        "transition_in": "cut",
        "lighting": "High-speed flash or bright ambient for fast shutter",
        "lens": "24-70mm f/2.8",
        "composition": "dynamic angle, motion blur option, peak action moment",
        "gemini_prompt_template": "{mannequin_description} in dynamic {action}, peak action moment, {environment}, fast shutter freeze, dramatic angle, sports/action photography, energy and movement captured",
        "kling_prompt_template": "Dynamic {action} movement, camera tracking subject, energetic motion, speed and power, {duration}s, cinematic action",
        "keywords": ["action", "dynamic", "movement", "sports photography", "energy"],
    },
    "montage": {
        "description": "Rapid sequence of related shots building energy",
        "optimal_duration": 2.5,
        "camera_movement": "zoom_in",
        "transition_in": "cut",
        "lighting": "Varied — each cut has different lighting for variety",
        "lens": "varies",
        "composition": "varied — each shot different angle/distance",
        "gemini_prompt_template": "{subject} in {angle} shot, {lighting}, {mood}, single moment captured, commercial photography, punchy and memorable",
        "kling_prompt_template": "Quick dynamic movement, {camera_action}, energetic pacing, {duration}s, montage rhythm",
        "keywords": ["montage", "quick cut", "varied angles", "energy building"],
    },
    "reveal": {
        "description": "Gradual product or mannequin reveal — building anticipation",
        "optimal_duration": 5.0,
        "camera_movement": "dolly_in",
        "transition_in": "dissolve",
        "lighting": "Starts dark/silhouette, light builds to full reveal",
        "lens": "85mm f/1.4",
        "composition": "starts obscured, ends full frame, controlled reveal",
        "gemini_prompt_template": "{subject} partially revealed, {obscuring_element}, dramatic lighting from behind, silhouette transitioning to full light, anticipation, cinematic reveal composition",
        "kling_prompt_template": "Slow dolly in revealing {subject}, light gradually building, dramatic shadow-to-light transition, {duration}s, cinematic tension",
        "keywords": ["reveal", "anticipation", "dramatic", "light build", "silhouette"],
    },
    "ambient": {
        "description": "Atmospheric filler — smoke, light rays, textures, abstract",
        "optimal_duration": 3.0,
        "camera_movement": "static",
        "transition_in": "dissolve",
        "lighting": "Atmospheric — volumetric, haze, light rays",
        "lens": "50mm f/1.2",
        "composition": "abstract or semi-abstract, mood-focused",
        "gemini_prompt_template": "Atmospheric {element}, volumetric light rays, {mood} ambiance, abstract quality, {color_tone} color grading, cinematic atmosphere, film grain",
        "kling_prompt_template": "Gentle ambient motion, {element} drifting slowly, light rays shifting, atmospheric particles, {duration}s, meditative pace",
        "keywords": ["ambient", "atmospheric", "abstract", "mood", "volumetric"],
    },
    "overhead_flat_lay": {
        "description": "Top-down product arrangement — popular in beauty/food",
        "optimal_duration": 4.0,
        "camera_movement": "zoom_out",
        "transition_in": "dissolve",
        "lighting": "Even overhead softbox, minimal shadows",
        "lens": "35mm f/4 (overhead)",
        "composition": "top-down, symmetrical or styled arrangement",
        "gemini_prompt_template": "Top-down flat lay of {products}, {surface_material} background, even overhead lighting, styled arrangement, {decorative_elements}, commercial flat lay photography, sharp throughout",
        "kling_prompt_template": "Camera slowly pulling back from top-down view, revealing full flat lay arrangement, {duration}s, smooth zoom out",
        "keywords": ["flat lay", "top-down", "arrangement", "overhead photography"],
    },
    "walking_tracking": {
        "description": "Mannequin walking while camera follows — fashion staple",
        "optimal_duration": 5.0,
        "camera_movement": "tracking",
        "transition_in": "fade",
        "lighting": "Natural or environmental",
        "lens": "70mm f/2.0",
        "composition": "full body or 3/4, environment visible, motion direction",
        "gemini_prompt_template": "{mannequin_description} walking in {environment}, mid-stride captured, {clothing} in motion, {lighting}, fashion editorial, camera-level perspective, depth of field",
        "kling_prompt_template": "Mannequin walking confidently, camera tracking alongside, fabric in motion, hair movement, environment passing by, {duration}s, smooth steadicam feel",
        "keywords": ["walking shot", "tracking", "fashion", "movement", "steadicam"],
    },
    "reflection_shot": {
        "description": "Product or mannequin seen in mirror, water, or glass reflection",
        "optimal_duration": 4.0,
        "camera_movement": "static",
        "transition_in": "dissolve",
        "lighting": "Dramatic — plays with reflection angles",
        "lens": "50mm f/2.0",
        "composition": "dual image — real + reflection, symmetry play",
        "gemini_prompt_template": "{subject} with reflection in {reflective_surface}, dual composition showing both real and reflected, dramatic lighting, {mood}, artistic photography, visual depth through reflection",
        "kling_prompt_template": "Subtle movement with reflection responding, light shifting across {reflective_surface}, {duration}s, artistic and contemplative",
        "keywords": ["reflection", "mirror", "dual image", "artistic", "symmetry"],
    },
    "silhouette": {
        "description": "Subject backlit creating dramatic silhouette outline",
        "optimal_duration": 4.0,
        "camera_movement": "static",
        "transition_in": "dissolve",
        "lighting": "Strong backlight, no fill — pure silhouette or semi-silhouette",
        "lens": "85mm f/2.0",
        "composition": "profile or 3/4, strong outline, light source visible or implied",
        "gemini_prompt_template": "{subject} silhouette against {light_source}, dramatic backlight, strong outline, {mood} atmosphere, cinematic silhouette photography, minimal detail in shadow",
        "kling_prompt_template": "Silhouette slowly moving, backlight shifting, atmospheric haze, {duration}s, dramatic and mysterious",
        "keywords": ["silhouette", "backlight", "dramatic", "outline", "mysterious"],
    },
    "slow_motion_detail": {
        "description": "Slow-motion capture of movement or material — fabric, liquid, hair",
        "optimal_duration": 4.0,
        "camera_movement": "static",
        "transition_in": "dissolve",
        "lighting": "High-speed lighting — bright, even, or dramatic spot",
        "lens": "100mm macro f/2.8",
        "composition": "tight framing on the moving element",
        "gemini_prompt_template": "Frozen moment of {element} in motion, high-speed photography, every detail visible, {material_texture}, dramatic lighting, commercial quality, 8K detail",
        "kling_prompt_template": "Ultra slow motion {element} movement, every detail visible, {material} physics, cinematic slow-mo, {duration}s",
        "keywords": ["slow motion", "detail", "frozen moment", "high-speed", "texture"],
    },
    "group_shot": {
        "description": "Multiple products or people in one frame",
        "optimal_duration": 4.0,
        "camera_movement": "pan_right",
        "transition_in": "fade",
        "lighting": "Even — all subjects equally lit",
        "lens": "35mm f/2.8",
        "composition": "balanced arrangement, all subjects visible, hierarchy clear",
        "gemini_prompt_template": "Group arrangement of {subjects}, balanced composition, all equally lit, {environment}, clear visual hierarchy, commercial group photography, sharp throughout",
        "kling_prompt_template": "Slow pan across {subjects}, each receiving camera attention, balanced movement, {duration}s",
        "keywords": ["group shot", "multiple subjects", "arrangement", "balanced"],
    },
    "split_screen": {
        "description": "Two contrasting scenes side by side (day/night, before/after)",
        "optimal_duration": 4.0,
        "camera_movement": "static",
        "transition_in": "wipe",
        "lighting": "Different per side — deliberate contrast",
        "lens": "50mm f/2.8",
        "composition": "vertical or horizontal split, contrasting but balanced",
        "gemini_prompt_template": "Split composition: left side {scene_a} with {lighting_a}, right side {scene_b} with {lighting_b}, deliberate contrast, commercial split-screen photography",
        "kling_prompt_template": "Static split screen with independent motion on each side, {duration}s, contrasting energy",
        "keywords": ["split screen", "contrast", "duality", "comparison"],
    },
    "hand_detail": {
        "description": "Close-up of hands interacting with product — applying, holding, touching",
        "optimal_duration": 4.0,
        "camera_movement": "static",
        "transition_in": "dissolve",
        "lighting": "Soft, flattering to skin, product lit separately",
        "lens": "100mm macro f/2.8",
        "composition": "tight on hands + product, minimal background",
        "gemini_prompt_template": "Close-up of elegant hands {interaction} with {product}, soft beauty lighting, {skin_quality}, {product_material} detail visible, macro commercial photography, intimate detail",
        "kling_prompt_template": "Gentle hand movement with {product}, fingers touching surface, product reacting to interaction, {duration}s, intimate and tactile",
        "keywords": ["hand detail", "tactile", "intimate", "product interaction", "macro"],
    },
    "environment_transition": {
        "description": "Scene shifting between two environments (indoor→outdoor, city→nature)",
        "optimal_duration": 5.0,
        "camera_movement": "pan_left",
        "transition_in": "dissolve",
        "lighting": "Transitions from one lighting mood to another",
        "lens": "24mm f/2.8",
        "composition": "wide enough to show both environments, transition point",
        "gemini_prompt_template": "{environment_a} transitioning to {environment_b}, liminal space between two worlds, {mood}, cinematic composition, environmental storytelling",
        "kling_prompt_template": "Camera panning from {environment_a} atmosphere to {environment_b}, lighting shifting, mood transforming, {duration}s, narrative transition",
        "keywords": ["environment transition", "dual mood", "narrative", "transformation"],
    },
    "360_product": {
        "description": "Complete rotation showing all angles of the product",
        "optimal_duration": 5.0,
        "camera_movement": "orbit",
        "transition_in": "dissolve",
        "lighting": "Consistent 360 lighting rig, even coverage",
        "lens": "90mm f/4",
        "composition": "center-frame, product on turntable or camera orbiting",
        "gemini_prompt_template": "{product} at {angle} angle, studio 360 lighting rig, {background}, every surface detail visible, commercial 360 product photography, sharp throughout",
        "kling_prompt_template": "Smooth continuous orbit around {product}, consistent lighting, full 360 rotation, reflections shifting naturally, {duration}s",
        "keywords": ["360 product", "orbit", "all angles", "turntable", "consistent lighting"],
    },
}

# Quick lookup helpers

def get_archetype(name: str) -> dict | None:
    """Get archetype by name, case-insensitive."""
    return SCENE_ARCHETYPES.get(name.lower())


def get_all_archetypes() -> list[str]:
    """List all available archetype names."""
    return list(SCENE_ARCHETYPES.keys())
